Set JAVAHOME before using it.

diff --git a/bin/ptinvoke.in b/bin/ptinvoke.in
--- a/bin/ptinvoke.in
+++ b/bin/ptinvoke.in
@@ -348,6 +348,43 @@ passHelpArgument=yes
 # Optional jar file
 jarfile="$ALL_JAR"
 
+# If JAVAHOME is not set, then try to set it
+if [ -z "$JAVAHOME" ]; then
+    if [ -d "$PTJAVA_DIR" ]; then
+	JAVAHOME="$PTJAVA_DIR"
+	export JAVAHOME
+    else
+	if [ "$windows" = "yes" ]; then
+	    searchfile=java.exe
+	else
+	    searchfile=java
+	fi
+	oldifs="$IFS"; IFS=":"
+	for i in $PATH
+	do
+	    if [ -x "$i/$searchfile" -a ! -d "$i/$searchfile" ]; then
+		JAVAHOME=`dirname $i`
+		export JAVAHOME
+		break
+	    fi
+	done
+	IFS="$oldifs"
+    fi
+    if [ -z "$JAVAHOME" ]; then
+	if [ -d "/usr/eesww/lang/jdk1.1latest" ]; then
+		# Locally, Java can sometimes be found here.
+		JAVAHOME=/usr/eesww/lang/jdk1.1latest
+	fi
+    fi
+    if [ -z "$JAVAHOME" ]; then
+	echo "$0: Could not find $searchfile in your \$PATH"
+	echo " Please set \$JAVAHOME to the directory that contains your"
+	echo " Java distribution"
+	exit 3
+    fi
+fi
+
+
 # The Java process to run.
 javac="$JAVAHOME/bin/java"
 
@@ -663,42 +700,6 @@ else
     Windows*)
 	windows=yes;;
     esac
-fi
-
-# If JAVAHOME is not set, then try to set it
-if [ -z "$JAVAHOME" ]; then
-    if [ -d "$PTJAVA_DIR" ]; then
-	JAVAHOME="$PTJAVA_DIR"
-	export JAVAHOME
-    else
-	if [ "$windows" = "yes" ]; then
-	    searchfile=java.exe
-	else
-	    searchfile=java
-	fi
-	oldifs="$IFS"; IFS=":"
-	for i in $PATH
-	do
-	    if [ -x "$i/$searchfile" -a ! -d "$i/$searchfile" ]; then
-		JAVAHOME=`dirname $i`
-		export JAVAHOME
-		break
-	    fi
-	done
-	IFS="$oldifs"
-    fi
-    if [ -z "$JAVAHOME" ]; then
-	if [ -d "/usr/eesww/lang/jdk1.1latest" ]; then
-		# Locally, Java can sometimes be found here.
-		JAVAHOME=/usr/eesww/lang/jdk1.1latest
-	fi
-    fi
-    if [ -z "$JAVAHOME" ]; then
-	echo "$0: Could not find $searchfile in your \$PATH"
-	echo " Please set \$JAVAHOME to the directory that contains your"
-	echo " Java distribution"
-	exit 3
-    fi
 fi
 
 jdbflags=""
