configure.in changed

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4456,6 +4456,7 @@ echo $ECHO_N "checking for Eclipse installation... $ECHO_C" >&6
 
     # We cd to *clipse so that we get the case right in the jar files.
     if test -d "c:/Program Files/Eclipse" -o -d "c:/Program Files/eclipse"; then
+    # Remove /cygdrive
        TMP_ECLIPSE_DIR="`cd c:/Program\ Files/*clipse; pwd | sed 's@/cygdrive/\([a-z]\)/@\1:/@'`"
     else
        TMP_ECLIPSE_DIR="c:/Program\ Files/eclipse"
@@ -4469,15 +4470,20 @@ else
   ECLIPSE_DIR=$TMP_ECLIPSE_DIR
 fi;
 
-    # Remove /cygdrive
-
 
     if test ! -d "$ECLIPSE_DIR"; then
 	{ echo "$as_me:$LINENO: WARNING: Failed to find Eclipse in $ECLIPSE_DIR" >&5
 echo "$as_me: WARNING: Failed to find Eclipse in $ECLIPSE_DIR" >&2;}
 	echo "$as_me:$LINENO: checking for $PTII/vendors/eclipse" >&5
 echo $ECHO_N "checking for $PTII/vendors/eclipse... $ECHO_C" >&6
-        # Extract the first word of "eclipse", so it can be a program name with args.
+   	if test -d  "$PTII/vendors/eclipse"; then
+	    echo "$as_me:$LINENO: result: ok" >&5
+echo "${ECHO_T}ok" >&6
+	    ECLIPSE_DIR="$PTII/vendors/eclipse"
+        else
+	    { echo "$as_me:$LINENO: WARNING: Failed to find Eclipse in $PTII/vendors/eclipse" >&5
+echo "$as_me: WARNING: Failed to find Eclipse in $PTII/vendors/eclipse" >&2;}
+            # Extract the first word of "eclipse", so it can be a program name with args.
 set dummy eclipse; ac_word=$2
 echo "$as_me:$LINENO: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
@@ -4516,11 +4522,11 @@ else
 echo "${ECHO_T}no" >&6
 fi
 
-   	if test -d  "$PTII/vendors/eclipse"; then
-	   ECLIPSE_DIR="$PTII/vendors/eclipse"
-        else
-           if test "${PTECLIPSE:-none}" != "none"; then
-	      ECLIPSE_DIR=`dirname $PTECLIPSE`
+            if test "${PTECLIPSE:-none}" != "none"; then
+            # Remove /cygdrive
+	    ECLIPSE_DIR=`dirname $PTECLIPSE | sed 's@/cygdrive/\([a-z]\)/@\1:/@'`
+	    echo "$as_me:$LINENO: result: $ECLIPSE_DIR" >&5
+echo "${ECHO_T}$ECLIPSE_DIR" >&6
 	   fi
         fi
     fi
