configure.in changed

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -717,6 +717,8 @@ KIELER_JAR
 KVM_CLASSES
 KVM_DIR
 LEJOS_DIR
+LIBXML2_INCLUDE_DIR
+LIBXML2_LIB_DIR
 MAJOR_OS_NAME
 MATLAB_DIR
 MATLAB_LIBDIR
@@ -788,6 +790,7 @@ PTKIELER_DIR
 PTKVM_DIR
 PTLEGO_DIR
 PTLEJOS_DIR
+PTLIBXML2_DIR
 PTMATLAB_CC_FLAGS
 PTMATLAB_DIR
 PTMATLAB_LD_ARGS
@@ -1486,6 +1489,8 @@ Optional Packages:
                           defaults to \$PTII/vendors/misc/waba/wabasdk
   --with-X10=DIR       use X10 from DIR,
                               defaults to \$PTII/vendors/misc/x10
+  --with-xml2-include=DIR       use libxml/xpath.h from DIR
+                          defaults to \$PTII/vendors/gc/gc/include
 
 Some influential environment variables:
   CC          C compiler command
@@ -5569,6 +5574,9 @@ echo $ECHO_N "checking for optional codegen packages on which to run javadoc... 
 	    PTCODEGEN_OPTIONAL_PACKAGES="$PTCODEGEN_OPTIONAL_PACKAGES $package"
         fi
     done
+    if test "${PTVERBOSE:-none}" = "none"; then { echo "$as_me:$LINENO: result: ok" >&5
+echo "${ECHO_T}ok" >&6; }; else { echo "$as_me:$LINENO: result: ok" >&5
+echo "${ECHO_T}ok" >&6; }; fi
 fi
 
 
@@ -6186,7 +6194,6 @@ if test -z "$PTBACKTRACK_ECLIPSE_DIR"; then
 fi
 
 #--------------------------------------------------------------------
-
 #       Garbage Collector (GC)
 #       The C code generator can use the Boehm Garbage Collector
 #       See http://www.hpl.hp.com/personal/Hans_Boehm/gc/
@@ -8340,9 +8347,9 @@ echo $ECHO_N "checking for jars used by jini... $ECHO_C" >&6; }
 	for jar in $JINI_JARS
 	do
 	    if test "${PTVERBOSE:-none}" = "none"; then
-	        echo $ECHO_N "."
+	        $PT_ECHO $ECHO_N "."
 	    else
-                echo $ECHO_N "$jar "
+                $PT_ECHO $ECHO_N "$jar "
             fi
 	    jarpath=`$FIND "$JINI_DIR" -name $jar | head -1`
    	    if test -f "$jarpath"; then
@@ -10387,6 +10394,189 @@ else
     <classpathentry kind=\"lib\" path=\"$X10_CLASSES\"/>"
 fi
 
+#--------------------------------------------------------------------
+#       libxml2 is used by the lbnl simulation interface in ptII/lbnl
+#--------------------------------------------------------------------
+
+# The include and lib dirs for libxml2
+LIBXML2_INCLUDE_DIR=
+LIBXML2_LIB_DIR=
+
+# PTLIBXML2_DIR is set util if LIBXML2_INCLUDE_DIR and LIBXML2_LIB_DIR are set
+PTLIBXML2_DIR=
+
+LIBXML2_USER_DIR=$PTII/lbnl/lib/util
+if test ! -d "$LIBXML2_USER_DIR"; then
+    if test "${PTVERBOSE:-none}" != "none"; then { echo "$as_me:$LINENO: result: $LIBXML2_USER_DIR is not present,
+    so we need not find libxml2." >&5
+echo "${ECHO_T}$LIBXML2_USER_DIR is not present,
+    so we need not find libxml2." >&6; }; fi
+else
+    # Extract the first word of "gcc", so it can be a program name with args.
+set dummy gcc; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_path_PTCC+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $PTCC in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_PTCC="$PTCC" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_path_PTCC="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+  ;;
+esac
+fi
+PTCC=$ac_cv_path_PTCC
+if test -n "$PTCC"; then
+  { echo "$as_me:$LINENO: result: $PTCC" >&5
+echo "${ECHO_T}$PTCC" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
+    if test "${PTCC:-none}" = "none"; then
+        { echo "$as_me:$LINENO: WARNING: Failed to find gcc" >&5
+echo "$as_me: WARNING: Failed to find gcc" >&2;}
+        # Extract the first word of "cc", so it can be a program name with args.
+set dummy cc; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_path_PTCC+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $PTCC in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_PTCC="$PTCC" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_path_PTCC="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+  ;;
+esac
+fi
+PTCC=$ac_cv_path_PTCC
+if test -n "$PTCC"; then
+  { echo "$as_me:$LINENO: result: $PTCC" >&5
+echo "${ECHO_T}$PTCC" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
+        if test "${PTCC:-none}" != "none"; then
+            if test "${PTVERBOSE:-none}" = "none"; then { echo "$as_me:$LINENO: result: ok" >&5
+echo "${ECHO_T}ok" >&6; }; else { echo "$as_me:$LINENO: result: $PTCC" >&5
+echo "${ECHO_T}$PTCC" >&6; }; fi
+        else
+            { echo "$as_me:$LINENO: WARNING: Failed to find gcc or cc, so we will
+    not be able use LIBXML2 in $LIBXML2_USER_DIR" >&5
+echo "$as_me: WARNING: Failed to find gcc or cc, so we will
+    not be able use LIBXML2 in $LIBXML2_USER_DIR" >&2;};
+        fi
+    fi
+
+    if test "${PTCC:-none}" != "none"; then
+       { echo "$as_me:$LINENO: checking for libxml2" >&5
+echo $ECHO_N "checking for libxml2... $ECHO_C" >&6; }
+       # FIXME: This will not work if $PTII has spaces
+       dirs="$PTII/vendors/libxml2 /usr/local/lib /usr/lib"
+       for dir in $dirs
+       do
+           if test -f "$dir/libxml2.${PTJNI_SHAREDLIBRARY_SUFFIX}"; then
+               if test "${PTVERBOSE:-none}" = "none"; then { echo "$as_me:$LINENO: result: ok" >&5
+echo "${ECHO_T}ok" >&6; }; else { echo "$as_me:$LINENO: result: $dir/libxml2.${PTJNI_SHAREDLIBRARY_SUFFIX}" >&5
+echo "${ECHO_T}$dir/libxml2.${PTJNI_SHAREDLIBRARY_SUFFIX}" >&6; }; fi
+	       LIBXML2_LIB_DIR=$dir
+	       break;
+           fi
+       done
+       if test ! -d "$LIBXML2_LIB_DIR"; then
+           { echo "$as_me:$LINENO: WARNING: Failed to find libxml2.${PTJNI_SHAREDLIBRARY_SUFFIX}
+    The LBNL Simulation facility in \$PTII/lbnl/lib/util requires libxml2.
+    However, Ptolemy will run without this facility." >&5
+echo "$as_me: WARNING: Failed to find libxml2.${PTJNI_SHAREDLIBRARY_SUFFIX}
+    The LBNL Simulation facility in \$PTII/lbnl/lib/util requires libxml2.
+    However, Ptolemy will run without this facility." >&2;}
+       fi
+    fi
+    { echo "$as_me:$LINENO: checking for libxml/xpath.h" >&5
+echo $ECHO_N "checking for libxml/xpath.h... $ECHO_C" >&6; }
+
+# Check whether --with-xml2-include was given.
+if test "${with_xml2_include+set}" = set; then
+  withval=$with_xml2_include; LIBXML2_INCLUDE_DIR=$withval
+else
+  LIBXML2_INCLUDE_DIR=/usr/include/libxml2
+fi
+
+
+    if test -f "$LIBXML2_INCLUDE_DIR/libxml/xpath.h"; then
+       if test "${PTVERBOSE:-none}" = "none"; then { echo "$as_me:$LINENO: result: ok" >&5
+echo "${ECHO_T}ok" >&6; }; else { echo "$as_me:$LINENO: result: $LIBXML2_INCLUDE_DIR/libxml/xpath.h" >&5
+echo "${ECHO_T}$LIBXML2_INCLUDE_DIR/libxml/xpath.h" >&6; }; fi
+    else
+       # FIXME: This will not work if $PTII has spaces
+       dirs="$PTII/vendors/libxml2 /usr/local/include /usr/include"
+       for dir in $dirs
+       do
+           if test -f "$dir/libxml/xpath.h"; then
+               LIBXML2_INCLUDE_DIR=$dir
+	       if test "${PTVERBOSE:-none}" = "none"; then { echo "$as_me:$LINENO: result: ok" >&5
+echo "${ECHO_T}ok" >&6; }; else { echo "$as_me:$LINENO: result: $LIBXML2_INCLUDE_DIR/libxml/xpath.h" >&5
+echo "${ECHO_T}$LIBXML2_INCLUDE_DIR/libxml/xpath.h" >&6; }; fi
+           fi
+       done
+       if test ! -f "$LIBXML2_INCLUDE_DIR/libxml/xpath.h"; then
+           { echo "$as_me:$LINENO: WARNING: Failed to find libxml/xpath.h
+    Checked the following directories:
+    $dirs
+    The LBNL Simulation facility in \$PTII/lbnl/lib/util requires libxml2.
+    However, Ptolemy will run without this facility." >&5
+echo "$as_me: WARNING: Failed to find libxml/xpath.h
+    Checked the following directories:
+    $dirs
+    The LBNL Simulation facility in \$PTII/lbnl/lib/util requires libxml2.
+    However, Ptolemy will run without this facility." >&2;}
+       fi
+   fi
+fi
+
+if test -f "$LIBXML2_INCLUDE_DIR/libxml/xpath.h" -a -f "$LIBXML2_LIB_DIR/libxml2.${PTJNI_SHAREDLIBRARY_SUFFIX}"; then
+   # Used in $PTII/lbnl/lib/util/makefile
+   PTLIBXML2_DIR=util
+fi
 
 # Keep these substitutions alphabetical, with a description
 
@@ -10543,6 +10733,12 @@ fi
 
 # Set to the location of the lejos installation, usually in
 # $PTII/vendors/lejos
+
+
+# Set to the directory that contains libxml/xpath.h and used in $PTII/lbnl/lib/util
+
+
+# Set to the directory that contains libxml  and used in $PTII/lbnl/lib/util
 
 
 # The major type of OS we are running under.
@@ -10808,6 +11004,9 @@ fi
 # Set to lejos and used in
 # $PTII/ptolemy/apps/makefile if the Java Communications API was found
 # and Legos was found
+
+
+# Set to util and used in $PTII/lbnl/lib/util/makefile if libxml2 was found
 
 
 # Set to gcc or cl and used in
@@ -11751,6 +11950,8 @@ KIELER_JAR!$KIELER_JAR$ac_delim
 KVM_CLASSES!$KVM_CLASSES$ac_delim
 KVM_DIR!$KVM_DIR$ac_delim
 LEJOS_DIR!$LEJOS_DIR$ac_delim
+LIBXML2_INCLUDE_DIR!$LIBXML2_INCLUDE_DIR$ac_delim
+LIBXML2_LIB_DIR!$LIBXML2_LIB_DIR$ac_delim
 MAJOR_OS_NAME!$MAJOR_OS_NAME$ac_delim
 MATLAB_DIR!$MATLAB_DIR$ac_delim
 MATLAB_LIBDIR!$MATLAB_LIBDIR$ac_delim
@@ -11822,6 +12023,7 @@ PTKIELER_DIR!$PTKIELER_DIR$ac_delim
 PTKVM_DIR!$PTKVM_DIR$ac_delim
 PTLEGO_DIR!$PTLEGO_DIR$ac_delim
 PTLEJOS_DIR!$PTLEJOS_DIR$ac_delim
+PTLIBXML2_DIR!$PTLIBXML2_DIR$ac_delim
 PTMATLAB_CC_FLAGS!$PTMATLAB_CC_FLAGS$ac_delim
 PTMATLAB_DIR!$PTMATLAB_DIR$ac_delim
 PTMATLAB_LD_ARGS!$PTMATLAB_LD_ARGS$ac_delim
@@ -11839,9 +12041,6 @@ PTSPACE_DIR!$PTSPACE_DIR$ac_delim
 PTSPACEDOMAIN_JAR!$PTSPACEDOMAIN_JAR$ac_delim
 PTSPACEDOMAIN_PACKAGES!$PTSPACEDOMAIN_PACKAGES$ac_delim
 PTTINI_DIR!$PTTINI_DIR$ac_delim
-PTTINYOS_DIR!$PTTINYOS_DIR$ac_delim
-PTGIOTTO_DIR!$PTGIOTTO_DIR$ac_delim
-PTVR_DIR!$PTVR_DIR$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -11883,6 +12082,9 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+PTTINYOS_DIR!$PTTINYOS_DIR$ac_delim
+PTGIOTTO_DIR!$PTGIOTTO_DIR$ac_delim
+PTVR_DIR!$PTVR_DIR$ac_delim
 PTVR_JAR!$PTVR_JAR$ac_delim
 PTVR_PACKAGES!$PTVR_PACKAGES$ac_delim
 PTWABA_DIR!$PTWABA_DIR$ac_delim
@@ -11909,7 +12111,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 24; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 27; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
