configure.in changed

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3048,7 +3048,15 @@ echo "${ECHO_T}ok, you are running $JVERSION" >&6; }; fi
 esac
 
 if test "$UPGRADE_JVM" = "yes"; then
-		{ { echo "$as_me:$LINENO: error: Ptolemy II requires JDK 1.4 or later.
+    case "`uname -s`" in
+        Darwin)
+     	    upgradeMessage="Under Mac OS X, to change the version of Java,
+    use the 'Java Preferences' program under /Applications/Utilities.";;
+        *)
+	    upgradeMessage="";;
+    esac
+
+		{ { echo "$as_me:$LINENO: error: Ptolemy II requires JDK 1.5 or later.
     JDK 1.2.2 has a bug involving compiling inner classes with protected
     methods.
     The RTOS domain uses java.util.Timer, which is present in JDK 1.3
@@ -3061,8 +3069,9 @@ if test "$UPGRADE_JVM" = "yes"; then
 	- backtrack
 	- ptalon
     JDK 1.6 or later is needed for ptdb to use javax.swing.GroupLayout.
-    Please upgrade your JDK to 1.6 or later and try again" >&5
-echo "$as_me: error: Ptolemy II requires JDK 1.4 or later.
+    Please upgrade your JDK to 1.6 or later and try again.
+    $upgradeMessage" >&5
+echo "$as_me: error: Ptolemy II requires JDK 1.5 or later.
     JDK 1.2.2 has a bug involving compiling inner classes with protected
     methods.
     The RTOS domain uses java.util.Timer, which is present in JDK 1.3
@@ -3075,7 +3084,8 @@ echo "$as_me: error: Ptolemy II requires JDK 1.4 or later.
 	- backtrack
 	- ptalon
     JDK 1.6 or later is needed for ptdb to use javax.swing.GroupLayout.
-    Please upgrade your JDK to 1.6 or later and try again" >&2;}
+    Please upgrade your JDK to 1.6 or later and try again.
+    $upgradeMessage" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
