configure.in changed

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -23,6 +23,9 @@ ac_help="$ac_help
   --with-ptjacl_jar=PTJACL.JAR  ptjacl.jar file,
                            used for running the test scripts"
 ac_help="$ac_help
+  --with-jini=DIR       use Jini from DIR,
+                          defaults to \$PTII/vendors/sun/$JINI_VERSION"
+ac_help="$ac_help
   --with-kvm=DIR       use PalmOS KVM from DIR,
                           defaults to \$PTII/vendors/sun/kvm"
 
@@ -594,7 +597,7 @@ so we search for the java compiler." 1>&2
     # Extract the first word of "javac", so it can be a program name with args.
 set dummy javac; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:598: checking for $ac_word" >&5
+echo "configure:601: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_JAVAC'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -663,15 +666,15 @@ fi
 # Check that we have the javac that corresponds with PTJAVA_DIR in our path
 #
 echo $ac_n "checking for the java runtime in $PTJAVA_DIR/bin""... $ac_c" 1>&6
-echo "configure:667: checking for the java runtime in $PTJAVA_DIR/bin" >&5
+echo "configure:670: checking for the java runtime in $PTJAVA_DIR/bin" >&5
 if test -f $PTJAVA_DIR/bin/java; then
     echo "$ac_t""$PTJAVA_DIR/bin/java" 1>&6
     echo $ac_n "checking that you have the right java in your path.""... $ac_c" 1>&6
-echo "configure:671: checking that you have the right java in your path." >&5
+echo "configure:674: checking that you have the right java in your path." >&5
     # Extract the first word of "java", so it can be a program name with args.
 set dummy java; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:675: checking for $ac_word" >&5
+echo "configure:678: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_JAVA'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -717,15 +720,15 @@ fi
 # Check that we have the javac that corresponds with PTJAVA_DIR in our path
 #
 echo $ac_n "checking for the java compiler in $PTJAVA_DIR/bin""... $ac_c" 1>&6
-echo "configure:721: checking for the java compiler in $PTJAVA_DIR/bin" >&5
+echo "configure:724: checking for the java compiler in $PTJAVA_DIR/bin" >&5
 if test -f $PTJAVA_DIR/bin/javac; then
     echo "$ac_t""$PTJAVA_DIR/bin/javac" 1>&6
     echo $ac_n "checking that you have the right javac in your path.""... $ac_c" 1>&6
-echo "configure:725: checking that you have the right javac in your path." >&5
+echo "configure:728: checking that you have the right javac in your path." >&5
     # Extract the first word of "javac", so it can be a program name with args.
 set dummy javac; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:729: checking for $ac_word" >&5
+echo "configure:732: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_JAVAC'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -768,10 +771,10 @@ fi
 
 
 #--------------------------------------------------------------------
-#	Figure out whether to use javac -Xdepend or javac -depend
+#	Test the Java Compiler (javac)
 #--------------------------------------------------------------------
 echo $ac_n "checking the Java compiler with a simple compile""... $ac_c" 1>&6
-echo "configure:775: checking the Java compiler with a simple compile" >&5
+echo "configure:778: checking the Java compiler with a simple compile" >&5
 # We need to run javac in the config directory so that javac from jdk1.1.6
 # under NT and cygwin works properly
 startdir=`pwd`
@@ -781,7 +784,7 @@ if $JAVAC confTest.java ; then
     echo "$ac_t""ok" 1>&6
 
     echo $ac_n "checking the value of the java.version Property ""... $ac_c" 1>&6
-echo "configure:785: checking the value of the java.version Property " >&5
+echo "configure:788: checking the value of the java.version Property " >&5
     # Strip out the JDK1.3beta messages under Solaris2.5.1
     JVERSION=`CLASSPATH=$PTII/config $JAVA confTest | 
 	grep -v "Warning! The libthread.so on your system is an older version than" |
@@ -789,33 +792,8 @@ echo "configure:785: checking the value of the java.version Property " >&5
 	grep -v "patch installation instructions."`	
     echo "$ac_t""$JVERSION" 1>&6
 
-    JDEPENDFLAG="-Xdepend"
-    echo $ac_n "checking javac $JDEPENDFLAG""... $ac_c" 1>&6
-echo "configure:795: checking javac $JDEPENDFLAG" >&5
-    if $JAVAC -d $startdir $JDEPENDFLAG confTest.java ; then
-	echo "$ac_t""yes" 1>&6
-    else
-	echo "$ac_t""no" 1>&6
-	JDEPENDFLAG="-depend"
-	echo $ac_n "checking javac $JDEPENDFLAG""... $ac_c" 1>&6
-echo "configure:802: checking javac $JDEPENDFLAG" >&5
-	if $JAVAC -d $startdir $JDEPENDFLAG confTest.java ; then
-	    echo "$ac_t""yes" 1>&6
-	else
-	    echo "$ac_t""no" 1>&6
-	    echo "configure: warning: '$JAVAC -d $startdir -Xdepend confTest.java' and
-'$JAVAC -d $startdir -depend confTest.java' both failed, so we don't
-know how to build with dependencies taken into account.  This could
-cause problems later if you modify .java files that other .java
-files depend on" 1>&2
-	    echo "$ac_t""$JDEPENDFLAG" 1>&6
-	fi
-    fi
 else
-    JDEPENDFLAG="-depend"
-   echo "configure: warning: '$JAVAC confTest.java' failed,
-so we can't figure out whether to use -Xdepend or -depend.
-Defaulting to $JDEPENDFLAG" 1>&2;
+   echo "configure: warning: '$JAVAC confTest.java' failed'" 1>&2
 fi
 cd $startdir
 
@@ -827,7 +805,7 @@ cd $startdir
 #       CYGWIN_NT-5.0 respectively)
 #--------------------------------------------------------------------
 echo $ac_n "checking for the proper CLASSPATH separator""... $ac_c" 1>&6
-echo "configure:831: checking for the proper CLASSPATH separator" >&5
+echo "configure:809: checking for the proper CLASSPATH separator" >&5
 
 case "`uname -s`" in
     CYGWIN_NT-*) CLASSPATHSEPARATOR=";";;
@@ -850,7 +828,7 @@ find JavaCC" 1>&6
     JJTREE=jjtree
 else
     echo $ac_n "checking for JavaCC""... $ac_c" 1>&6
-echo "configure:854: checking for JavaCC" >&5
+echo "configure:832: checking for JavaCC" >&5
     # Check whether --with-javacc or --without-javacc was given.
 if test "${with_javacc+set}" = set; then
   withval="$with_javacc"
@@ -872,7 +850,7 @@ so we search for the jjtree command." 1>&2
 	    # Extract the first word of "jjtree", so it can be a program name with args.
 set dummy jjtree; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:876: checking for $ac_word" >&5
+echo "configure:854: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_JJTREE'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -911,7 +889,7 @@ fi
 	if test -d "$JAVACC_DIR"; then
 	    echo "$ac_t""$JAVACC_DIR" 1>&6
 	    echo $ac_n "checking for jjtree""... $ac_c" 1>&6
-echo "configure:915: checking for jjtree" >&5
+echo "configure:893: checking for jjtree" >&5
 	    if test -x "$JAVACC_DIR/bin/jjtree"; then
 		# Note that we don't substitute in the $(JAVACC_DIR) here
 		JJTREE='$(JAVACC_DIR)/bin/jjtree'
@@ -920,7 +898,7 @@ echo "configure:915: checking for jjtree" >&5
 		echo "configure: warning: Failed to find jjtree in '$JAVACC_DIR/bin'" 1>&2;
 	    fi    
 	    echo $ac_n "checking for javacc""... $ac_c" 1>&6
-echo "configure:924: checking for javacc" >&5
+echo "configure:902: checking for javacc" >&5
 	    if test -x "$JAVACC_DIR/bin/javacc"; then
 		# Note that we don't substitute in the $(JAVACC_DIR) here
 		JAVACC='$(JAVACC_DIR)/bin/javacc'
@@ -959,7 +937,7 @@ if test ! -d "$PTII/util/testsuite"; then
 find Jacl" 1>&6
 else
     echo $ac_n "checking for ptjacl.jar""... $ac_c" 1>&6
-echo "configure:963: checking for ptjacl.jar" >&5
+echo "configure:941: checking for ptjacl.jar" >&5
     # Check whether --with-ptjacl_jar or --without-ptjacl_jar was given.
 if test "${with_ptjacl_jar+set}" = set; then
   withval="$with_ptjacl_jar"
@@ -972,7 +950,7 @@ fi
     if test -f "$PTJACL_JAR"; then
 	echo "$ac_t""$PTJACL_JAR" 1>&6
 	echo $ac_n "checking for how to run jacl""... $ac_c" 1>&6
-echo "configure:976: checking for how to run jacl" >&5
+echo "configure:954: checking for how to run jacl" >&5
 	# This command starts up Jacl
 	if echo "set java::jdkVersion; exit" | CLASSPATH=$PTJACL_JAR $JAVA $PTJACL_JFLAG tcl.lang.Shell; then
 		echo "$ac_t""CLASSPATH=$PTJACL_JAR $JAVA $PTJACL_JFLAG tcl.lang.Shell" 1>&6
@@ -988,6 +966,50 @@ echo "configure:976: checking for how to run jacl" >&5
   You can download ptjacl.jar from
   http://ptolemy.eecs.berkeley.edu/~cxh/java/jacl/ptjacl.html" 1>&2
     fi	 
+fi
+
+#--------------------------------------------------------------------
+#       Jini is connection technology from Sun, see http://www.sun.com/jini/
+#	See if there was a command-line option for where
+#       kvm/tools/classes.zip is;  if not,
+#       check to see if $PTII/vendors/sun/kvm exists
+#--------------------------------------------------------------------
+
+# We only need to look for kvm if $PTII/ptolemy/kvm exists
+JINI_USER_DIR="$PTII/ptolemy/domains/ct/demo/CarTracking"
+JINI_VERSION=jini1_0_1
+JINI_PRESENT=no
+if test ! -d "$JINI_USER_DIR"; then
+    echo "$ac_t""$JINI_USER_DIR is not present, so we need not
+find Jini" 1>&6
+    # We don't use JINI_VERSION here so that we don't expand PTII
+    # in the makefile	
+    JINI_DIR='$(PTII)/vendors/sun/jini/jini1_0_1'
+else
+    echo $ac_n "checking for jini directory""... $ac_c" 1>&6
+echo "configure:991: checking for jini directory" >&5
+    # Check whether --with-jini or --without-jini was given.
+if test "${with_jini+set}" = set; then
+  withval="$with_jini"
+  JINI_DIR=$withval
+else
+  JINI_DIR=$PTII/vendors/sun/jini/$JINI_VERSION
+fi
+
+
+    if test -d "$JINI_DIR"; then
+	echo "$ac_t""$JINI_DIR" 1>&6
+	JINI_PRESENT=yes
+    else    
+	JINI_DIR='$(PTII)/vendors/sun/$JINI_VERSION'
+    fi    
+    if test "$JINI_PRESENT" = "no"; then
+        echo "configure: warning: 'Failed to find $JINI_DIR/lib/jini-core.jar
+  Perhaps Jini is not installed?
+  You need not download Jini unless you plan on use Jini and JavaSpaces
+  Jini can be downloaded from http://java.sun.com/jini' and placed
+  in \$PTII/vendors/sun/jini/$JINI_VERSION" 1>&2
+    fi	
 fi
 
 
@@ -1007,7 +1029,7 @@ find the PalmOS kvm" 1>&6
     KVM_CLASSES='$(KVM_DIR)/tools/classes.zip'
 else
     echo $ac_n "checking for kvm directory""... $ac_c" 1>&6
-echo "configure:1011: checking for kvm directory" >&5
+echo "configure:1033: checking for kvm directory" >&5
     # Check whether --with-kvm or --without-kvm was given.
 if test "${with_kvm+set}" = set; then
   withval="$with_kvm"
@@ -1020,7 +1042,7 @@ fi
     if test -d "$KVM_DIR"; then
 	echo "$ac_t""$KVM_DIR" 1>&6
         echo $ac_n "checking for \$KVM_DIR/tools/classes.zip""... $ac_c" 1>&6
-echo "configure:1024: checking for \$KVM_DIR/tools/classes.zip" >&5
+echo "configure:1046: checking for \$KVM_DIR/tools/classes.zip" >&5
 	if test -f "$KVM_DIR/tools/classes.zip"; then
 	    KVM_CLASSES='$(KVM_DIR)/tools/classes.zip'
 	    echo "$ac_t""$KVM_CLASSES" 1>&6
@@ -1053,7 +1075,10 @@ fi
 # Directory that contains JavaCC, which is used in ptolemy/data/expr
 
 
-# Arguments to pass to javac.  Usually something like '-g -depend'
+# Jini home directory, see http://www.sun.com/jini/
+
+
+# If Jini is present, the set to yes, otherwise, set to no
 
 
 # jtclsh script, used for test suites
@@ -1232,7 +1257,8 @@ s%@JJTREE@%$JJTREE%g
 s%@CLASSPATHSEPARATOR@%$CLASSPATHSEPARATOR%g
 s%@JAVACC@%$JAVACC%g
 s%@JAVACC_DIR@%$JAVACC_DIR%g
-s%@JDEPENDFLAG@%$JDEPENDFLAG%g
+s%@JINI_DIR@%$JINI_DIR%g
+s%@JINI_PRESENT@%$JINI_PRESENT%g
 s%@JTCLSH@%$JTCLSH%g
 s%@JTREE@%$JTREE%g
 s%@JVERSION@%$JVERSION%g
