configure.in changed

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -31,6 +31,9 @@ ac_help="$ac_help
 ac_help="$ac_help
   --with-kvm=DIR       use PalmOS KVM from DIR,
                           defaults to \$PTII/vendors/sun/j2me_cldc"
+ac_help="$ac_help
+  --with-waba=DIR       use PalmOS WABA from DIR,
+                          defaults to \$PTII/vendors/misc/waba/wabasdk"
 
 # Initialize some variables set by options.
 # The variables have the same names as the options, with
@@ -606,7 +609,7 @@ so we search for the java compiler." 1>&2
     # Extract the first word of "javac", so it can be a program name with args.
 set dummy javac; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:610: checking for $ac_word" >&5
+echo "configure:613: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_JAVAC'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -675,15 +678,15 @@ fi
 # Check that we have the javac that corresponds with PTJAVA_DIR in our path
 #
 echo $ac_n "checking for the java runtime in $PTJAVA_DIR/bin""... $ac_c" 1>&6
-echo "configure:679: checking for the java runtime in $PTJAVA_DIR/bin" >&5
+echo "configure:682: checking for the java runtime in $PTJAVA_DIR/bin" >&5
 if test -f $PTJAVA_DIR/bin/java -o -f $PTJAVA_DIR/bin/java.exe; then
     echo "$ac_t""$PTJAVA_DIR/bin/java" 1>&6
     echo $ac_n "checking that you have the right java in your path.""... $ac_c" 1>&6
-echo "configure:683: checking that you have the right java in your path." >&5
+echo "configure:686: checking that you have the right java in your path." >&5
     # Extract the first word of "java", so it can be a program name with args.
 set dummy java; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:687: checking for $ac_word" >&5
+echo "configure:690: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_JAVA'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -729,15 +732,15 @@ fi
 # Check that we have the javac that corresponds with PTJAVA_DIR in our path
 #
 echo $ac_n "checking for the java compiler in $PTJAVA_DIR/bin""... $ac_c" 1>&6
-echo "configure:733: checking for the java compiler in $PTJAVA_DIR/bin" >&5
+echo "configure:736: checking for the java compiler in $PTJAVA_DIR/bin" >&5
 if test -f $PTJAVA_DIR/bin/javac; then
     echo "$ac_t""$PTJAVA_DIR/bin/javac" 1>&6
     echo $ac_n "checking that you have the right javac in your path.""... $ac_c" 1>&6
-echo "configure:737: checking that you have the right javac in your path." >&5
+echo "configure:740: checking that you have the right javac in your path." >&5
     # Extract the first word of "javac", so it can be a program name with args.
 set dummy javac; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:741: checking for $ac_word" >&5
+echo "configure:744: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_JAVAC'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -783,7 +786,7 @@ fi
 #	Test the Java Compiler (javac)
 #--------------------------------------------------------------------
 echo $ac_n "checking the Java compiler with a simple compile""... $ac_c" 1>&6
-echo "configure:787: checking the Java compiler with a simple compile" >&5
+echo "configure:790: checking the Java compiler with a simple compile" >&5
 # We need to run javac in the config directory so that javac from jdk1.1.6
 # under NT and cygwin works properly
 startdir=`pwd`
@@ -793,7 +796,7 @@ if $JAVAC confTest.java ; then
     echo "$ac_t""ok" 1>&6
 
     echo $ac_n "checking the value of the java.version Property ""... $ac_c" 1>&6
-echo "configure:797: checking the value of the java.version Property " >&5
+echo "configure:800: checking the value of the java.version Property " >&5
     # Strip out the JDK1.3beta messages under Solaris2.5.1
     JVERSION=`CLASSPATH=$PTII/config $JAVA confTest | 
 	grep -v "Warning! The libthread.so on your system is an older version than" |
@@ -814,7 +817,7 @@ cd $startdir
 #       CYGWIN_NT-5.0 respectively)
 #--------------------------------------------------------------------
 echo $ac_n "checking for the proper CLASSPATH separator""... $ac_c" 1>&6
-echo "configure:818: checking for the proper CLASSPATH separator" >&5
+echo "configure:821: checking for the proper CLASSPATH separator" >&5
 
 case "`uname -s`" in
     CYGWIN_NT-*) CLASSPATHSEPARATOR=";";;
@@ -827,7 +830,7 @@ case "`uname -s`" in
 	# Extract the first word of "cmd", so it can be a program name with args.
 set dummy cmd; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:831: checking for $ac_word" >&5
+echo "configure:834: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_CMD_PATH'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -900,7 +903,7 @@ find commapi" 1>&6
     COMMAPI_DIR='$(PTII)/vendors/sun/commapi'
 else
     echo $ac_n "checking for commapi directory""... $ac_c" 1>&6
-echo "configure:904: checking for commapi directory" >&5
+echo "configure:907: checking for commapi directory" >&5
     # Check whether --with-COMMAPI or --without-COMMAPI was given.
 if test "${with_COMMAPI+set}" = set; then
   withval="$with_COMMAPI"
@@ -945,7 +948,7 @@ find JavaCC" 1>&6
     JJTREE=jjtree
 else
     echo $ac_n "checking for JavaCC""... $ac_c" 1>&6
-echo "configure:949: checking for JavaCC" >&5
+echo "configure:952: checking for JavaCC" >&5
     # Check whether --with-javacc or --without-javacc was given.
 if test "${with_javacc+set}" = set; then
   withval="$with_javacc"
@@ -967,7 +970,7 @@ so we search for the jjtree command." 1>&2
 	    # Extract the first word of "jjtree", so it can be a program name with args.
 set dummy jjtree; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:971: checking for $ac_word" >&5
+echo "configure:974: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_JJTREE'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -1006,7 +1009,7 @@ fi
 	if test -d "$JAVACC_DIR"; then
 	    echo "$ac_t""$JAVACC_DIR" 1>&6
 	    echo $ac_n "checking for jjtree""... $ac_c" 1>&6
-echo "configure:1010: checking for jjtree" >&5
+echo "configure:1013: checking for jjtree" >&5
 	    if test -x "$JAVACC_DIR/bin/jjtree"; then
 		# Note that we don't substitute in the $(JAVACC_DIR) here
 		JJTREE='$(JAVACC_DIR)/bin/jjtree'
@@ -1015,7 +1018,7 @@ echo "configure:1010: checking for jjtree" >&5
 		echo "configure: warning: Failed to find jjtree in '$JAVACC_DIR/bin'" 1>&2;
 	    fi    
 	    echo $ac_n "checking for javacc""... $ac_c" 1>&6
-echo "configure:1019: checking for javacc" >&5
+echo "configure:1022: checking for javacc" >&5
 	    if test -x "$JAVACC_DIR/bin/javacc"; then
 		# Note that we don't substitute in the $(JAVACC_DIR) here
 		JAVACC='$(JAVACC_DIR)/bin/javacc'
@@ -1054,7 +1057,7 @@ if test ! -d "$PTII/util/testsuite"; then
 find Jacl" 1>&6
 else
     echo $ac_n "checking for ptjacl.jar""... $ac_c" 1>&6
-echo "configure:1058: checking for ptjacl.jar" >&5
+echo "configure:1061: checking for ptjacl.jar" >&5
     # Check whether --with-ptjacl_jar or --without-ptjacl_jar was given.
 if test "${with_ptjacl_jar+set}" = set; then
   withval="$with_ptjacl_jar"
@@ -1067,7 +1070,7 @@ fi
     if test -f "$PTJACL_JAR"; then
 	echo "$ac_t""$PTJACL_JAR" 1>&6
 	echo $ac_n "checking for how to run jacl""... $ac_c" 1>&6
-echo "configure:1071: checking for how to run jacl" >&5
+echo "configure:1074: checking for how to run jacl" >&5
 	# This command starts up Jacl
 	if echo "set java::jdkVersion; exit" | CLASSPATH=$PTJACL_JAR $JAVA $PTJACL_JFLAG tcl.lang.Shell; then
 		echo "$ac_t""CLASSPATH=$PTJACL_JAR $JAVA $PTJACL_JFLAG tcl.lang.Shell" 1>&6
@@ -1093,7 +1096,7 @@ fi
 PTJAVASOUND_DIR=
 
 echo $ac_n "checking for javax.sound""... $ac_c" 1>&6
-echo "configure:1097: checking for javax.sound" >&5
+echo "configure:1100: checking for javax.sound" >&5
 # We need to run javac in the config directory so that javac from jdk1.1.6
 # under NT and cygwin works properly
 startdir=`pwd`
@@ -1130,7 +1133,7 @@ if test ! -d "$JINI_USER_DIR"; then
     JINI_DIR='\$PTII/vendors/sun/jini/jini1_0_1'
 else
     echo $ac_n "checking for jini directory""... $ac_c" 1>&6
-echo "configure:1134: checking for jini directory" >&5
+echo "configure:1137: checking for jini directory" >&5
     # Check whether --with-jini or --without-jini was given.
 if test "${with_jini+set}" = set; then
   withval="$with_jini"
@@ -1167,13 +1170,13 @@ fi
 #       check to see if $PTII/vendors/sun/j2me_cldc exists
 #--------------------------------------------------------------------
 
-# PTKVM_DIR is set to jspaces and used in 
+# PTKVM_DIR is set to kvm and used in 
 # $PTII/ptolemy/makefile if kvm was found
 PTKVM_DIR=
 #
-# We only need to look for kvm if $PTII/ptolemy/kvm exists
-if test ! -d "$PTII/ptolemy/kvm"; then
-    echo "$ac_t""$PTII/ptolemy/kvm is not present, so we need not
+# We only need to look for kvm if $PTII/ptolemy/apps/kvm exists
+if test ! -d "$PTII/ptolemy/apps/kvm"; then
+    echo "$ac_t""$PTII/ptolemy/apps/kvm is not present, so we need not
 find the PalmOS kvm" 1>&6
     KVM_DIR='$(PTII)/vendors/sun/j2me_cldc'
     # Unfortunately, j2me_cldc does not ship with a jar of zip file
@@ -1181,7 +1184,7 @@ find the PalmOS kvm" 1>&6
     KVM_CLASSES='$(KVM_DIR)/bin/api/classes'
 else
     echo $ac_n "checking for kvm directory""... $ac_c" 1>&6
-echo "configure:1185: checking for kvm directory" >&5
+echo "configure:1188: checking for kvm directory" >&5
     # Check whether --with-kvm or --without-kvm was given.
 if test "${with_kvm+set}" = set; then
   withval="$with_kvm"
@@ -1194,7 +1197,7 @@ fi
     if test -d "$KVM_DIR"; then
 	echo "$ac_t""$KVM_DIR" 1>&6
         echo $ac_n "checking for \$KVM_DIR/bin/api/classes""... $ac_c" 1>&6
-echo "configure:1198: checking for \$KVM_DIR/bin/api/classes" >&5
+echo "configure:1201: checking for \$KVM_DIR/bin/api/classes" >&5
 	if test -d "$KVM_DIR/bin/api/classes"; then
 	    KVM_CLASSES='$(KVM_DIR)/bin/api/classes'
 	    echo "$ac_t""$KVM_CLASSES" 1>&6
@@ -1204,13 +1207,13 @@ echo "configure:1198: checking for \$KVM_DIR/bin/api/classes" >&5
     else    
 	echo "$ac_t""Not found in $KVM_DIR" 1>&6
 	echo $ac_n "checking for kvm directory in /j2me_cldc""... $ac_c" 1>&6
-echo "configure:1208: checking for kvm directory in /j2me_cldc" >&5
+echo "configure:1211: checking for kvm directory in /j2me_cldc" >&5
 	# Likely place for kvm under windows
 	KVM_DIR=/j2me_cldc
         if test -d "$KVM_DIR"; then
 	    echo "$ac_t""$KVM_DIR" 1>&6
             echo $ac_n "checking for \$KVM_DIR/bin/api/classes""... $ac_c" 1>&6
-echo "configure:1214: checking for \$KVM_DIR/bin/api/classes" >&5
+echo "configure:1217: checking for \$KVM_DIR/bin/api/classes" >&5
 	    if test -d "$KVM_DIR/bin/api/classes"; then
 	        KVM_CLASSES='$(KVM_DIR)/bin/api/classes'
 	        echo "$ac_t""$KVM_CLASSES" 1>&6
@@ -1235,6 +1238,84 @@ Kvm can be downloaded from http://java.sun.com/products/cldc'" 1>&2
 	# Set to kvm and used in 
 	# $PTII/ptolemy/makefile if kvm was found
 	PTKVM_DIR=kvm
+    fi    
+fi
+
+#--------------------------------------------------------------------
+#       WABA is the JDK for PalmOS
+#	See if there was a command-line option for where
+#       wabask is;  if not,
+#       check to see if $PTII/vendors/misc/waba/wabasdk exists
+#--------------------------------------------------------------------
+
+# PTWABA_DIR is set to waba and used in 
+# $PTII/ptolemy/makefile if waba was found
+PTWABA_DIR=
+#
+# We only need to look for waba if $PTII/ptolemy/apps/kvm exists
+if test ! -d "$PTII/ptolemy/apps/kvm"; then
+    echo "$ac_t""$PTII/ptolemy/apps/kvm is not present, so we need not
+find the PalmOS waba" 1>&6
+    WABA_DIR='$(PTII)/vendors/misc/waba/wabasdk'
+    # Unfortunately, j2me_cldc does not ship with a jar of zip file
+    # It needs to be built	
+    WABA_CLASSES='$(WABA_DIR)/classes'
+else
+    echo $ac_n "checking for waba directory""... $ac_c" 1>&6
+echo "configure:1266: checking for waba directory" >&5
+    # Check whether --with-waba or --without-waba was given.
+if test "${with_waba+set}" = set; then
+  withval="$with_waba"
+  WABA_DIR=$withval
+else
+  WABA_DIR=$PTII/vendors/misc/waba/wabasdk
+fi
+
+
+    if test -d "$WABA_DIR"; then
+	echo "$ac_t""$WABA_DIR" 1>&6
+        echo $ac_n "checking for \$WABA_DIR/classes""... $ac_c" 1>&6
+echo "configure:1279: checking for \$WABA_DIR/classes" >&5
+	if test -d "$WABA_DIR/classes"; then
+	    WABA_CLASSES='$(WABA_DIR)/classes'
+	    echo "$ac_t""$WABA_CLASSES" 1>&6
+        else
+	    WABA_CLASSES=no
+        fi
+    else    
+	echo "$ac_t""Not found in $WABA_DIR" 1>&6
+	echo $ac_n "checking for waba directory in /waba""... $ac_c" 1>&6
+echo "configure:1289: checking for waba directory in /waba" >&5
+	# Likely place for waba under windows
+	WABA_DIR=/waba/wabasdk
+        if test -d "$WABA_DIR"; then
+	    echo "$ac_t""$WABA_DIR" 1>&6
+            echo $ac_n "checking for \$WABA_DIR/classes""... $ac_c" 1>&6
+echo "configure:1295: checking for \$WABA_DIR/classes" >&5
+	    if test -d "$WABA_DIR/classes"; then
+	        WABA_CLASSES='$(WABA_DIR)/classes'
+	        echo "$ac_t""$WABA_CLASSES" 1>&6
+            else
+	        WABA_CLASSES=no
+            fi
+        else 
+		WABA_CLASSES=no
+        fi
+
+    fi
+    if test "$WABA_CLASSES" = "no"; then
+        echo "configure: warning: 'Failed to find waba/wabasdk
+perhaps Waba is not installed?
+You need not download Waba unless you plan on building applications
+for the Palm Pilot or Handspring Visor.
+Waba can be downloaded from http://www.wabasoft.com'" 1>&2
+	# Note that we don't substitute in the $(PTII) or $(WABA_DIR) here
+	WABA_DIR='$(PTII)/vendors/misc/waba/wabasdk'
+   	WABA_CLASSES='$(WABA_DIR)/classes'
+    else 
+	# Set to waba and used in 
+	# $PTII/ptolemy/makefile if waba was found
+	PTWABA_DIR=waba
     fi    
 fi
 
@@ -1294,14 +1375,25 @@ fi
 
 
 # Set to kvm and used in 
-# $PTII/ptolemy/makefile if kvm was found
+# $PTII/ptolemy/apps/makefile if kvm was found
 
 
 # Set to lego and used in 
 # $PTII/ptolemy/apps/makefile if the Java Communications API was found
 
 
+# Set to waba and used in 
+# $PTII/ptolemy/apps/makefile if Waba was found
+
+
 # Location of the PtII directory
+
+
+# waba/tools/classes.jar file used by the PalmOS WABA
+
+
+# Directory that contains the waba used by PalmOS
+
 
 
 # Files we substitute in
@@ -1470,7 +1562,10 @@ s%@PTJAVASOUND_DIR@%$PTJAVASOUND_DIR%g
 s%@PTJSPACES_DIR@%$PTJSPACES_DIR%g
 s%@PTKVM_DIR@%$PTKVM_DIR%g
 s%@PTLEGO_DIR@%$PTLEGO_DIR%g
+s%@PTWABA_DIR@%$PTWABA_DIR%g
 s%@PTII_DEFAULT@%$PTII_DEFAULT%g
+s%@WABA_CLASSES@%$WABA_CLASSES%g
+s%@WABA_DIR@%$WABA_DIR%g
 
 CEOF
 EOF
