configure.in changed

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -22,6 +22,9 @@ ac_help="$ac_help
 ac_help="$ac_help
   --with-ptjacl_jar=PTJACL.JAR  ptjacl.jar file,
                            used for running the test scripts"
+ac_help="$ac_help
+  --with-kvm=DIR       use PalmOS KVM from DIR,
+                          defaults to \$PTII/vendors/sun/kvm"
 
 # Initialize some variables set by options.
 # The variables have the same names as the options, with
@@ -591,7 +594,7 @@ so we search for the java compiler." 1>&2
     # Extract the first word of "javac", so it can be a program name with args.
 set dummy javac; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:595: checking for $ac_word" >&5
+echo "configure:598: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_JAVAC'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -660,15 +663,15 @@ fi
 # Check that we have the javac that corresponds with PTJAVA_DIR in our path
 #
 echo $ac_n "checking for the java runtime in $PTJAVA_DIR/bin""... $ac_c" 1>&6
-echo "configure:664: checking for the java runtime in $PTJAVA_DIR/bin" >&5
+echo "configure:667: checking for the java runtime in $PTJAVA_DIR/bin" >&5
 if test -f $PTJAVA_DIR/bin/java; then
     echo "$ac_t""$PTJAVA_DIR/bin/java" 1>&6
     echo $ac_n "checking that you have the right java in your path.""... $ac_c" 1>&6
-echo "configure:668: checking that you have the right java in your path." >&5
+echo "configure:671: checking that you have the right java in your path." >&5
     # Extract the first word of "java", so it can be a program name with args.
 set dummy java; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:672: checking for $ac_word" >&5
+echo "configure:675: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_JAVA'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -714,15 +717,15 @@ fi
 # Check that we have the javac that corresponds with PTJAVA_DIR in our path
 #
 echo $ac_n "checking for the java compiler in $PTJAVA_DIR/bin""... $ac_c" 1>&6
-echo "configure:718: checking for the java compiler in $PTJAVA_DIR/bin" >&5
+echo "configure:721: checking for the java compiler in $PTJAVA_DIR/bin" >&5
 if test -f $PTJAVA_DIR/bin/javac; then
     echo "$ac_t""$PTJAVA_DIR/bin/javac" 1>&6
     echo $ac_n "checking that you have the right javac in your path.""... $ac_c" 1>&6
-echo "configure:722: checking that you have the right javac in your path." >&5
+echo "configure:725: checking that you have the right javac in your path." >&5
     # Extract the first word of "javac", so it can be a program name with args.
 set dummy javac; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:726: checking for $ac_word" >&5
+echo "configure:729: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_JAVAC'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -768,7 +771,7 @@ fi
 #	Figure out whether to use javac -Xdepend or javac -depend
 #--------------------------------------------------------------------
 echo $ac_n "checking the Java compiler with a simple compile""... $ac_c" 1>&6
-echo "configure:772: checking the Java compiler with a simple compile" >&5
+echo "configure:775: checking the Java compiler with a simple compile" >&5
 # We need to run javac in the config directory so that javac from jdk1.1.6
 # under NT and cygwin works properly
 startdir=`pwd`
@@ -778,7 +781,7 @@ if $JAVAC confTest.java ; then
     echo "$ac_t""ok" 1>&6
 
     echo $ac_n "checking the value of the java.version Property ""... $ac_c" 1>&6
-echo "configure:782: checking the value of the java.version Property " >&5
+echo "configure:785: checking the value of the java.version Property " >&5
     # Strip out the JDK1.3beta messages under Solaris2.5.1
     JVERSION=`CLASSPATH=$PTII/config $JAVA confTest | 
 	grep -v "Warning! The libthread.so on your system is an older version than" |
@@ -788,14 +791,14 @@ echo "configure:782: checking the value of the java.version Property " >&5
 
     JDEPENDFLAG="-Xdepend"
     echo $ac_n "checking javac $JDEPENDFLAG""... $ac_c" 1>&6
-echo "configure:792: checking javac $JDEPENDFLAG" >&5
+echo "configure:795: checking javac $JDEPENDFLAG" >&5
     if $JAVAC -d $startdir $JDEPENDFLAG confTest.java ; then
 	echo "$ac_t""yes" 1>&6
     else
 	echo "$ac_t""no" 1>&6
 	JDEPENDFLAG="-depend"
 	echo $ac_n "checking javac $JDEPENDFLAG""... $ac_c" 1>&6
-echo "configure:799: checking javac $JDEPENDFLAG" >&5
+echo "configure:802: checking javac $JDEPENDFLAG" >&5
 	if $JAVAC -d $startdir $JDEPENDFLAG confTest.java ; then
 	    echo "$ac_t""yes" 1>&6
 	else
@@ -822,7 +825,7 @@ cd $startdir
 #	So much for write once, run everywhere.
 #--------------------------------------------------------------------
 echo $ac_n "checking for the proper CLASSPATH separator""... $ac_c" 1>&6
-echo "configure:826: checking for the proper CLASSPATH separator" >&5
+echo "configure:829: checking for the proper CLASSPATH separator" >&5
 case "`uname -s`" in
     CYGWIN_NT-4.0) CLASSPATHSEPARATOR=";";;
     *) CLASSPATHSEPARATOR=":";;
@@ -844,7 +847,7 @@ find JavaCC" 1>&6
     JJTREE=jjtree
 else
     echo $ac_n "checking for JavaCC""... $ac_c" 1>&6
-echo "configure:848: checking for JavaCC" >&5
+echo "configure:851: checking for JavaCC" >&5
     # Check whether --with-javacc or --without-javacc was given.
 if test "${with_javacc+set}" = set; then
   withval="$with_javacc"
@@ -865,7 +868,7 @@ so we search for the jjtree command." 1>&2
 	    # Extract the first word of "jjtree", so it can be a program name with args.
 set dummy jjtree; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:869: checking for $ac_word" >&5
+echo "configure:872: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_JJTREE'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -904,7 +907,7 @@ fi
 	if test -d "$JAVACC_DIR"; then
 	    echo "$ac_t""$JAVACC_DIR" 1>&6
 	    echo $ac_n "checking for jjtree""... $ac_c" 1>&6
-echo "configure:908: checking for jjtree" >&5
+echo "configure:911: checking for jjtree" >&5
 	    if test -x "$JAVACC_DIR/bin/jjtree"; then
 		# Note that we don't substitute in the $(JAVACC_DIR) here
 		JJTREE='$(JAVACC_DIR)/bin/jjtree'
@@ -913,7 +916,7 @@ echo "configure:908: checking for jjtree" >&5
 		echo "configure: warning: Failed to find jjtree in '$JAVACC_DIR/bin'" 1>&2;
 	    fi    
 	    echo $ac_n "checking for javacc""... $ac_c" 1>&6
-echo "configure:917: checking for javacc" >&5
+echo "configure:920: checking for javacc" >&5
 	    if test -x "$JAVACC_DIR/bin/javacc"; then
 		# Note that we don't substitute in the $(JAVACC_DIR) here
 		JAVACC='$(JAVACC_DIR)/bin/javacc'
@@ -970,7 +973,7 @@ if test ! -d "$PTII/util/testsuite"; then
 find Jacl" 1>&6
 else
     echo $ac_n "checking for ptjacl.jar""... $ac_c" 1>&6
-echo "configure:974: checking for ptjacl.jar" >&5
+echo "configure:977: checking for ptjacl.jar" >&5
     # Check whether --with-ptjacl_jar or --without-ptjacl_jar was given.
 if test "${with_ptjacl_jar+set}" = set; then
   withval="$with_ptjacl_jar"
@@ -983,7 +986,7 @@ fi
     if test -f "$PTJACL_JAR"; then
 	echo "$ac_t""$PTJACL_JAR" 1>&6
 	echo $ac_n "checking for how to run jacl""... $ac_c" 1>&6
-echo "configure:987: checking for how to run jacl" >&5
+echo "configure:990: checking for how to run jacl" >&5
 	# This command starts up Jacl
 	if echo "set java::jdkVersion; exit" | CLASSPATH=$PTJACL_JAR $JAVA $PTJACL_JFLAG tcl.lang.Shell; then
 		echo "$ac_t""CLASSPATH=$PTJACL_JAR $JAVA $PTJACL_JFLAG tcl.lang.Shell" 1>&6
@@ -1002,6 +1005,56 @@ echo "configure:987: checking for how to run jacl" >&5
 fi
 
 
+
+#--------------------------------------------------------------------
+#       KVM is the JDK for PalmOS
+#	See if there was a command-line option for where
+#       kvm/tools/classes.zip is;  if not,
+#       check to see if $PTII/vendors/sun/kvm exists
+#--------------------------------------------------------------------
+
+# We only need to look for kvm if $PTII/ptolemy/kvm exists
+if test ! -d "$PTII/ptolemy/kvm"; then
+    echo "$ac_t""$PTII/ptolemy/kvm is not present, so we need not
+find the PalmOS kvm" 1>&6
+    KVM_DIR='$(PTII)/vendors/sun/kvm'
+    KVM_CLASSES='$(KVM_DIR)/tools/classes.zip'
+else
+    echo $ac_n "checking for kvm directory""... $ac_c" 1>&6
+echo "configure:1025: checking for kvm directory" >&5
+    # Check whether --with-kvm or --without-kvm was given.
+if test "${with_kvm+set}" = set; then
+  withval="$with_kvm"
+  KVM_DIR=$withval
+else
+  KVM_DIR=$PTII/vendors/sun/kvm
+fi
+
+
+    if test -d "$KVM_DIR"; then
+	echo "$ac_t""$KVM_DIR" 1>&6
+        echo $ac_n "checking for \$KVM_DIR/tools/classes.zip""... $ac_c" 1>&6
+echo "configure:1038: checking for \$KVM_DIR/tools/classes.zip" >&5
+	if test -f "$KVM_DIR/tools/classes.zip"; then
+	    KVM_CLASSES='$(KVM_DIR)/tools/classes.zip'
+	    echo "$ac_t""$KVM_CLASSES" 1>&6
+        else
+	    KVM_CLASSES=no
+        fi
+    else    
+	KVM_CLASSES=no
+    fi
+    if test "$KVM_CLASSES" = "no"; then
+        echo "configure: warning: 'Failed to find kvm/tools/classes.zip,
+perhaps Kvm is not installed?
+You need not download Kvm unless you plan on building applications
+for the PalmPilot or Handspring Visor.
+Kvm can be downloaded from http://java.sun.com/products/kvm'" 1>&2
+	# Note that we don't substitute in the $(PTII) here
+	KVM_DIR='$(PTII)/vendors/sun/kvm'
+   	KVM_CLASSES='$(KVM_DIR)/tools/classes.zip'
+    fi    
+fi
 
 # Keep these substitutions alphabetical, with a description
 
@@ -1029,6 +1082,12 @@ fi
 
 
 # JDK Version determined by running confTest.class and getting java.version
+
+
+# kvm/tools/classes.jar file used by the PalmOS KVM
+
+
+# Directory that contains the kvm used by PalmOS
 
 
 # ptjacl.jar file, used to run the test suites
@@ -1197,6 +1256,8 @@ s%@JDEPENDFLAG@%$JDEPENDFLAG%g
 s%@JTCLSH@%$JTCLSH%g
 s%@JTREE@%$JTREE%g
 s%@JVERSION@%$JVERSION%g
+s%@KVM_CLASSES@%$KVM_CLASSES%g
+s%@KVM_DIR@%$KVM_DIR%g
 s%@PTJACL_JAR@%$PTJACL_JAR%g
 s%@PTJACL_JFLAG@%$PTJACL_JFLAG%g
 s%@PTJAVA_DIR@%$PTJAVA_DIR%g
