configure.in changed

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1860,7 +1860,6 @@ fi
     fi
 fi
 
-
 # Substitute %20 for any spaces.
 PTII_LOCALURL=`echo "file:///$PTII_DIR" | sed 's/ /%20/g'`
 #--------------------------------------------------------------------
@@ -1956,7 +1955,85 @@ echo "$as_me: WARNING:  Found javac in \"$JAVABIN\", /usr/java exists, so
   we are setting PTJAVA_DIR to '$PTJAVA_DIR'" >&2;}
 	    fi
 	fi
+        if test "$PTJAVA_DIR" = "/usr"; then
+	    # $PTII/vendors/ptinyos/tinyos-1.x/contrib/ptII/ptinyos/tools/make/ptII/ptII.rules
+	    # uses -I$(PTJAVA_DIR).  If PTJAVA_DIR is /usr, then compilation of the ptinyos
+	    # demos fails.
+	    echo "$as_me:$LINENO: checking PTJAVA_DIR == /usr, checking for links" >&5
+echo $ECHO_N "checking PTJAVA_DIR == /usr, checking for links... $ECHO_C" >&6
+	    startdir=$PTII
+	    cd "$srcdir/config"
+	    if "$JAVAC" RootDirectory.java ; then
+	        echo "$as_me:$LINENO: checking the value of the Java directory " >&5
+echo $ECHO_N "checking the value of the Java directory ... $ECHO_C" >&6
+		# Extract the first word of "java", so it can be a program name with args.
+set dummy java; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_JAVA+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $JAVA in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_JAVA="$JAVA" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_JAVA="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
 
+  ;;
+esac
+fi
+JAVA=$ac_cv_path_JAVA
+
+if test -n "$JAVA"; then
+  echo "$as_me:$LINENO: result: $JAVA" >&5
+echo "${ECHO_T}$JAVA" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+		set -x
+		if env CLASSPATH="$PTII/config" "$JAVA" RootDirectory "$JAVAC"> /dev/null; then
+
+		    PTJAVA_DIR_TMP=`CLASSPATH="$PTII/config" "$JAVA" RootDirectory "$JAVAC"`
+
+		    # Use changequote to protect the square brackets in sed
+	            # Remove /cygdrive so we can compile with MSVC
+		    #PTJAVA_DIR_REAL=`echo "$PTJAVA_HOME_TMP" | sed 's@/cygdrive/\([a-zA-Z]\)/@\1:/@'`
+       	            if test -d "$PTJAVA_DIR_TMP"; then
+		        PTJAVA_DIR="$PTJAVA_DIR_TMP"
+		        if test "${PTVERBOSE:-none}" = "none"; then echo "$as_me:$LINENO: result: ok" >&5
+echo "${ECHO_T}ok" >&6; else echo "$as_me:$LINENO: result: '$PTJAVA_DIR'" >&5
+echo "${ECHO_T}'$PTJAVA_DIR'" >&6; fi ;
+		    else
+		        { echo "$as_me:$LINENO: WARNING: 'CLASSPATH=\"$PTII/config\" $JAVA RootDirectory \"$JAVAC\"' failed.
+    We will not be able to search for the canonical Java home directory." >&5
+echo "$as_me: WARNING: 'CLASSPATH=\"$PTII/config\" $JAVA RootDirectory \"$JAVAC\"' failed.
+    We will not be able to search for the canonical Java home directory." >&2;};
+		    fi
+	        else
+		    { echo "$as_me:$LINENO: WARNING: 'CLASSPATH=\"$PTII/config\" $JAVAC RootDirectory.java' failed.
+    We will not be able to search for the canonical Java home directory." >&5
+echo "$as_me: WARNING: 'CLASSPATH=\"$PTII/config\" $JAVAC RootDirectory.java' failed.
+    We will not be able to search for the canonical Java home directory." >&2;};
+	        fi
+	        cd "$startdir"
+		set +x
+            fi
+        fi
     else
         { echo "$as_me:$LINENO: WARNING:  Failed to find javac, perhaps Java is not installed?" >&5
 echo "$as_me: WARNING:  Failed to find javac, perhaps Java is not installed?" >&2;}
@@ -9482,12 +9559,12 @@ echo "$as_me: WARNING: Failed to find matlab executable in the path.
 	else
 	    startdir=$PTII
 	    cd "$srcdir/config"
-	    if "$JAVAC" MatlabRootDirectory.java ; then
+	    if "$JAVAC" RootDirectory.java ; then
 		echo "$as_me:$LINENO: checking the value of the Matlab root directory " >&5
 echo $ECHO_N "checking the value of the Matlab root directory ... $ECHO_C" >&6
-		if env CLASSPATH="$PTII/config" "$JAVA" MatlabRootDirectory "$MATLAB"> /dev/null; then
+		if env CLASSPATH="$PTII/config" "$JAVA" RootDirectory "$MATLAB"> /dev/null; then
 
-		    MATLAB_DIR_TMP=`CLASSPATH="$PTII/config" "$JAVA" MatlabRootDirectory "$MATLAB"`
+		    MATLAB_DIR_TMP=`CLASSPATH="$PTII/config" "$JAVA" RootDirectory "$MATLAB"`
 
 		    # Use changequote to protect the square brackets in sed
 		    # Remove /cygdrive so we can compile with MSVC
@@ -9497,15 +9574,15 @@ echo $ECHO_N "checking the value of the Matlab root directory ... $ECHO_C" >&6
 echo "${ECHO_T}ok" >&6; else echo "$as_me:$LINENO: result: '$MATLAB_DIR'" >&5
 echo "${ECHO_T}'$MATLAB_DIR'" >&6; fi
 		else
-		    { echo "$as_me:$LINENO: WARNING: 'CLASSPATH=\"$PTII/config\" $JAVA MatlabRootDirectory \"$MATLAB\"' failed.
+		    { echo "$as_me:$LINENO: WARNING: 'CLASSPATH=\"$PTII/config\" $JAVA RootDirectory \"$MATLAB\"' failed.
     We will not be able to compile the Matlab interface in ptolemy/matlab/" >&5
-echo "$as_me: WARNING: 'CLASSPATH=\"$PTII/config\" $JAVA MatlabRootDirectory \"$MATLAB\"' failed.
+echo "$as_me: WARNING: 'CLASSPATH=\"$PTII/config\" $JAVA RootDirectory \"$MATLAB\"' failed.
     We will not be able to compile the Matlab interface in ptolemy/matlab/" >&2;};
 		fi
 	    else
-		{ echo "$as_me:$LINENO: WARNING: 'CLASSPATH=\"$PTII/config\" $JAVAC MatlabRootDirectory.java' failed.
+		{ echo "$as_me:$LINENO: WARNING: 'CLASSPATH=\"$PTII/config\" $JAVAC RootDirectory.java' failed.
     We will not be able to compile the Matlab interface in ptolemy/matlab" >&5
-echo "$as_me: WARNING: 'CLASSPATH=\"$PTII/config\" $JAVAC MatlabRootDirectory.java' failed.
+echo "$as_me: WARNING: 'CLASSPATH=\"$PTII/config\" $JAVAC RootDirectory.java' failed.
     We will not be able to compile the Matlab interface in ptolemy/matlab" >&2;};
 	    fi
 	    cd "$startdir"
