configure.in changed

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -32,6 +32,9 @@ ac_help="$ac_help
   --with-kvm=DIR       use PalmOS KVM from DIR,
                           defaults to \$PTII/vendors/sun/j2me_cldc"
 ac_help="$ac_help
+  --with-tini=DIR       use TINI from DIR,
+                          defaults to \$PTII/vendors/dalsemi/tini"
+ac_help="$ac_help
   --with-waba=DIR       use PalmOS WABA from DIR,
                           defaults to \$PTII/vendors/misc/waba/wabasdk"
 
@@ -609,7 +612,7 @@ so we search for the java compiler." 1>&2
     # Extract the first word of "javac", so it can be a program name with args.
 set dummy javac; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:613: checking for $ac_word" >&5
+echo "configure:616: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_JAVAC'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -678,15 +681,15 @@ fi
 # Check that we have the javac that corresponds with PTJAVA_DIR in our path
 #
 echo $ac_n "checking for the java runtime in $PTJAVA_DIR/bin""... $ac_c" 1>&6
-echo "configure:682: checking for the java runtime in $PTJAVA_DIR/bin" >&5
+echo "configure:685: checking for the java runtime in $PTJAVA_DIR/bin" >&5
 if test -f $PTJAVA_DIR/bin/java -o -f $PTJAVA_DIR/bin/java.exe; then
     echo "$ac_t""$PTJAVA_DIR/bin/java" 1>&6
     echo $ac_n "checking that you have the right java in your path.""... $ac_c" 1>&6
-echo "configure:686: checking that you have the right java in your path." >&5
+echo "configure:689: checking that you have the right java in your path." >&5
     # Extract the first word of "java", so it can be a program name with args.
 set dummy java; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:690: checking for $ac_word" >&5
+echo "configure:693: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_JAVA'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -732,15 +735,15 @@ fi
 # Check that we have the javac that corresponds with PTJAVA_DIR in our path
 #
 echo $ac_n "checking for the java compiler in $PTJAVA_DIR/bin""... $ac_c" 1>&6
-echo "configure:736: checking for the java compiler in $PTJAVA_DIR/bin" >&5
+echo "configure:739: checking for the java compiler in $PTJAVA_DIR/bin" >&5
 if test -f $PTJAVA_DIR/bin/javac; then
     echo "$ac_t""$PTJAVA_DIR/bin/javac" 1>&6
     echo $ac_n "checking that you have the right javac in your path.""... $ac_c" 1>&6
-echo "configure:740: checking that you have the right javac in your path." >&5
+echo "configure:743: checking that you have the right javac in your path." >&5
     # Extract the first word of "javac", so it can be a program name with args.
 set dummy javac; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:744: checking for $ac_word" >&5
+echo "configure:747: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_JAVAC'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -786,7 +789,7 @@ fi
 #	Test the Java Compiler (javac)
 #--------------------------------------------------------------------
 echo $ac_n "checking the Java compiler with a simple compile""... $ac_c" 1>&6
-echo "configure:790: checking the Java compiler with a simple compile" >&5
+echo "configure:793: checking the Java compiler with a simple compile" >&5
 # We need to run javac in the config directory so that javac from jdk1.1.6
 # under NT and cygwin works properly
 startdir=`pwd`
@@ -796,7 +799,7 @@ if $JAVAC confTest.java ; then
     echo "$ac_t""ok" 1>&6
 
     echo $ac_n "checking the value of the java.version Property ""... $ac_c" 1>&6
-echo "configure:800: checking the value of the java.version Property " >&5
+echo "configure:803: checking the value of the java.version Property " >&5
     # Strip out the JDK1.3beta messages under Solaris2.5.1
     JVERSION=`CLASSPATH=$PTII/config $JAVA confTest | 
 	grep -v "Warning! The libthread.so on your system is an older version than" |
@@ -817,7 +820,7 @@ cd $startdir
 #       CYGWIN_NT-5.0 respectively)
 #--------------------------------------------------------------------
 echo $ac_n "checking for the proper CLASSPATH separator""... $ac_c" 1>&6
-echo "configure:821: checking for the proper CLASSPATH separator" >&5
+echo "configure:824: checking for the proper CLASSPATH separator" >&5
 
 case "`uname -s`" in
     CYGWIN_NT-*) CLASSPATHSEPARATOR=";";;
@@ -830,7 +833,7 @@ case "`uname -s`" in
 	# Extract the first word of "cmd", so it can be a program name with args.
 set dummy cmd; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:834: checking for $ac_word" >&5
+echo "configure:837: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_CMD_PATH'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -903,7 +906,7 @@ find commapi" 1>&6
     COMMAPI_DIR='$(PTII)/vendors/sun/commapi'
 else
     echo $ac_n "checking for commapi directory""... $ac_c" 1>&6
-echo "configure:907: checking for commapi directory" >&5
+echo "configure:910: checking for commapi directory" >&5
     # Check whether --with-COMMAPI or --without-COMMAPI was given.
 if test "${with_COMMAPI+set}" = set; then
   withval="$with_COMMAPI"
@@ -948,7 +951,7 @@ find JavaCC" 1>&6
     JJTREE=jjtree
 else
     echo $ac_n "checking for JavaCC""... $ac_c" 1>&6
-echo "configure:952: checking for JavaCC" >&5
+echo "configure:955: checking for JavaCC" >&5
     # Check whether --with-javacc or --without-javacc was given.
 if test "${with_javacc+set}" = set; then
   withval="$with_javacc"
@@ -970,7 +973,7 @@ so we search for the jjtree command." 1>&2
 	    # Extract the first word of "jjtree", so it can be a program name with args.
 set dummy jjtree; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:974: checking for $ac_word" >&5
+echo "configure:977: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_JJTREE'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -1009,7 +1012,7 @@ fi
 	if test -d "$JAVACC_DIR"; then
 	    echo "$ac_t""$JAVACC_DIR" 1>&6
 	    echo $ac_n "checking for jjtree""... $ac_c" 1>&6
-echo "configure:1013: checking for jjtree" >&5
+echo "configure:1016: checking for jjtree" >&5
 	    if test -x "$JAVACC_DIR/bin/jjtree"; then
 		# Note that we don't substitute in the $(JAVACC_DIR) here
 		JJTREE='$(JAVACC_DIR)/bin/jjtree'
@@ -1018,7 +1021,7 @@ echo "configure:1013: checking for jjtree" >&5
 		echo "configure: warning: Failed to find jjtree in '$JAVACC_DIR/bin'" 1>&2;
 	    fi    
 	    echo $ac_n "checking for javacc""... $ac_c" 1>&6
-echo "configure:1022: checking for javacc" >&5
+echo "configure:1025: checking for javacc" >&5
 	    if test -x "$JAVACC_DIR/bin/javacc"; then
 		# Note that we don't substitute in the $(JAVACC_DIR) here
 		JAVACC='$(JAVACC_DIR)/bin/javacc'
@@ -1057,7 +1060,7 @@ if test ! -d "$PTII/util/testsuite"; then
 find Jacl" 1>&6
 else
     echo $ac_n "checking for ptjacl.jar""... $ac_c" 1>&6
-echo "configure:1061: checking for ptjacl.jar" >&5
+echo "configure:1064: checking for ptjacl.jar" >&5
     # Check whether --with-ptjacl_jar or --without-ptjacl_jar was given.
 if test "${with_ptjacl_jar+set}" = set; then
   withval="$with_ptjacl_jar"
@@ -1070,7 +1073,7 @@ fi
     if test -f "$PTJACL_JAR"; then
 	echo "$ac_t""$PTJACL_JAR" 1>&6
 	echo $ac_n "checking for how to run jacl""... $ac_c" 1>&6
-echo "configure:1074: checking for how to run jacl" >&5
+echo "configure:1077: checking for how to run jacl" >&5
 	# This command starts up Jacl
 	if echo "set java::jdkVersion; exit" | CLASSPATH=$PTJACL_JAR $JAVA $PTJACL_JFLAG tcl.lang.Shell; then
 		echo "$ac_t""CLASSPATH=$PTJACL_JAR $JAVA $PTJACL_JFLAG tcl.lang.Shell" 1>&6
@@ -1102,7 +1105,7 @@ if test ! -d "$JAVA3D_USER_DIR"; then
   is not present, so we need not find Java 3D" 1>&6
 else
     echo $ac_n "checking for Java 3D""... $ac_c" 1>&6
-echo "configure:1106: checking for Java 3D" >&5
+echo "configure:1109: checking for Java 3D" >&5
     # We need to run javac in the config directory so that javac from jdk1.1.6
     # under NT and cygwin works properly
     startdir=`pwd`
@@ -1129,7 +1132,7 @@ cd $startdir
 PTJAVASOUND_DIR=
 
 echo $ac_n "checking for javax.sound""... $ac_c" 1>&6
-echo "configure:1133: checking for javax.sound" >&5
+echo "configure:1136: checking for javax.sound" >&5
 # We need to run javac in the config directory so that javac from jdk1.1.6
 # under NT and cygwin works properly
 startdir=`pwd`
@@ -1166,7 +1169,7 @@ if test ! -d "$JINI_USER_DIR"; then
     JINI_DIR='\$PTII/vendors/sun/jini/jini1_0_1'
 else
     echo $ac_n "checking for jini directory""... $ac_c" 1>&6
-echo "configure:1170: checking for jini directory" >&5
+echo "configure:1173: checking for jini directory" >&5
     # Check whether --with-jini or --without-jini was given.
 if test "${with_jini+set}" = set; then
   withval="$with_jini"
@@ -1217,7 +1220,7 @@ find the PalmOS kvm" 1>&6
     KVM_CLASSES='$(KVM_DIR)/bin/api/classes'
 else
     echo $ac_n "checking for kvm directory""... $ac_c" 1>&6
-echo "configure:1221: checking for kvm directory" >&5
+echo "configure:1224: checking for kvm directory" >&5
     # Check whether --with-kvm or --without-kvm was given.
 if test "${with_kvm+set}" = set; then
   withval="$with_kvm"
@@ -1230,7 +1233,7 @@ fi
     if test -d "$KVM_DIR"; then
 	echo "$ac_t""$KVM_DIR" 1>&6
         echo $ac_n "checking for \$KVM_DIR/bin/api/classes""... $ac_c" 1>&6
-echo "configure:1234: checking for \$KVM_DIR/bin/api/classes" >&5
+echo "configure:1237: checking for \$KVM_DIR/bin/api/classes" >&5
 	if test -d "$KVM_DIR/bin/api/classes"; then
 	    KVM_CLASSES='$(KVM_DIR)/bin/api/classes'
 	    echo "$ac_t""$KVM_CLASSES" 1>&6
@@ -1240,13 +1243,13 @@ echo "configure:1234: checking for \$KVM_DIR/bin/api/classes" >&5
     else    
 	echo "$ac_t""Not found in $KVM_DIR" 1>&6
 	echo $ac_n "checking for kvm directory in /j2me_cldc""... $ac_c" 1>&6
-echo "configure:1244: checking for kvm directory in /j2me_cldc" >&5
+echo "configure:1247: checking for kvm directory in /j2me_cldc" >&5
 	# Likely place for kvm under windows
 	KVM_DIR=/j2me_cldc
         if test -d "$KVM_DIR"; then
 	    echo "$ac_t""$KVM_DIR" 1>&6
             echo $ac_n "checking for \$KVM_DIR/bin/api/classes""... $ac_c" 1>&6
-echo "configure:1250: checking for \$KVM_DIR/bin/api/classes" >&5
+echo "configure:1253: checking for \$KVM_DIR/bin/api/classes" >&5
 	    if test -d "$KVM_DIR/bin/api/classes"; then
 	        KVM_CLASSES='$(KVM_DIR)/bin/api/classes'
 	        echo "$ac_t""$KVM_CLASSES" 1>&6
@@ -1275,6 +1278,83 @@ Kvm can be downloaded from http://java.sun.com/products/cldc'" 1>&2
 fi
 
 #--------------------------------------------------------------------
+#       TINI is the JDK for Dallas Tini board, see
+#	www.ibutton.com
+#	See if there was a command-line option for where
+#       tinisk is;  if not,
+#       check to see if $PTII/vendors/dalsemi/tini/bin/tiniclasses.jar exists
+#--------------------------------------------------------------------
+
+# PTTINI_DIR is set to tini and used in 
+# $PTII/ptolemy/apps/makefile if tini was found
+PTTINI_DIR=
+#
+# We only need to look for tini if $PTII/ptolemy/apps/tini exists
+if test ! -d "$PTII/ptolemy/apps/tini"; then
+    echo "$ac_t""$PTII/ptolemy/apps/tini is not present, so we need not
+find the Dallas Semiconductor tini" 1>&6
+    TINI_DIR='$(PTII)/vendors/dalsemi/tini'
+    TINI_CLASSES='$(TINI_DIR)/bin/tiniclasses.jar'
+else
+    echo $ac_n "checking for tini directory""... $ac_c" 1>&6
+echo "configure:1301: checking for tini directory" >&5
+    # Check whether --with-tini or --without-tini was given.
+if test "${with_tini+set}" = set; then
+  withval="$with_tini"
+  TINI_DIR=$withval
+else
+  TINI_DIR=$PTII/vendors/dalsemi/tini
+fi
+
+
+    if test -d "$TINI_DIR"; then
+	echo "$ac_t""$TINI_DIR" 1>&6
+        echo $ac_n "checking for \$TINI_DIR/bin/tiniclasses.jar""... $ac_c" 1>&6
+echo "configure:1314: checking for \$TINI_DIR/bin/tiniclasses.jar" >&5
+	if test -f "$TINI_DIR/bin/tiniclasses.jar"; then
+	    TINI_CLASSES='$(TINI_DIR)/bin/tiniclasses.jar'
+	    echo "$ac_t""$TINI_CLASSES" 1>&6
+        else
+	    TINI_CLASSES=no
+        fi
+    else    
+	echo "$ac_t""Not found in $TINI_DIR" 1>&6
+	echo $ac_n "checking for tini directory in /tini""... $ac_c" 1>&6
+echo "configure:1324: checking for tini directory in /tini" >&5
+	# Likely place for tini under windows
+	TINI_DIR=/tini
+        if test -d "$TINI_DIR"; then
+	    echo "$ac_t""$TINI_DIR" 1>&6
+            echo $ac_n "checking for \$TINI_DIR/bin/tiniclasses.jar""... $ac_c" 1>&6
+echo "configure:1330: checking for \$TINI_DIR/bin/tiniclasses.jar" >&5
+	    if test -f "$TINI_DIR/bin/tiniclasses.jar"; then
+	        TINI_CLASSES='$(TINI_DIR)/bin/tiniclasses.jar'
+	        echo "$ac_t""$TINI_CLASSES" 1>&6
+            else
+	        TINI_CLASSES=no
+            fi
+        else 
+		TINI_CLASSES=no
+        fi
+
+    fi
+    if test "$TINI_CLASSES" = "no"; then
+        echo "configure: warning: 'Failed to find tini/bin/tiniclasses.jar
+   perhaps Tini is not installed?
+   You need not download Tini unless you plan on building applications
+   for the Dallas Semiconductor Tini board.
+   The Tini SDK can be downloaded from http://www.ibutton.com'" 1>&2
+	# Note that we don't substitute in the $(PTII) or $(TINI_DIR) here
+	TINI_DIR='$(PTII)/vendors/dalsemi/tini'
+   	TINI_CLASSES='$(TINI_DIR)/bin/tiniclasses.jar'
+    else 
+	# Set to tini and used in 
+	# $PTII/ptolemy/apps/makefile if tini was found
+	PTTINI_DIR=tini
+    fi    
+fi
+
+#--------------------------------------------------------------------
 #       WABA is the JDK for PalmOS
 #	See if there was a command-line option for where
 #       wabask is;  if not,
@@ -1295,7 +1375,7 @@ find the PalmOS waba" 1>&6
     WABA_CLASSES='$(WABA_DIR)/classes'
 else
     echo $ac_n "checking for waba directory""... $ac_c" 1>&6
-echo "configure:1299: checking for waba directory" >&5
+echo "configure:1379: checking for waba directory" >&5
     # Check whether --with-waba or --without-waba was given.
 if test "${with_waba+set}" = set; then
   withval="$with_waba"
@@ -1308,7 +1388,7 @@ fi
     if test -d "$WABA_DIR"; then
 	echo "$ac_t""$WABA_DIR" 1>&6
         echo $ac_n "checking for \$WABA_DIR/classes""... $ac_c" 1>&6
-echo "configure:1312: checking for \$WABA_DIR/classes" >&5
+echo "configure:1392: checking for \$WABA_DIR/classes" >&5
 	if test -d "$WABA_DIR/classes"; then
 	    WABA_CLASSES='$(WABA_DIR)/classes'
 	    echo "$ac_t""$WABA_CLASSES" 1>&6
@@ -1318,13 +1398,13 @@ echo "configure:1312: checking for \$WABA_DIR/classes" >&5
     else    
 	echo "$ac_t""Not found in $WABA_DIR" 1>&6
 	echo $ac_n "checking for waba directory in /waba""... $ac_c" 1>&6
-echo "configure:1322: checking for waba directory in /waba" >&5
+echo "configure:1402: checking for waba directory in /waba" >&5
 	# Likely place for waba under windows
 	WABA_DIR=/waba/wabasdk
         if test -d "$WABA_DIR"; then
 	    echo "$ac_t""$WABA_DIR" 1>&6
             echo $ac_n "checking for \$WABA_DIR/classes""... $ac_c" 1>&6
-echo "configure:1328: checking for \$WABA_DIR/classes" >&5
+echo "configure:1408: checking for \$WABA_DIR/classes" >&5
 	    if test -d "$WABA_DIR/classes"; then
 	        WABA_CLASSES='$(WABA_DIR)/classes'
 	        echo "$ac_t""$WABA_CLASSES" 1>&6
@@ -1419,11 +1499,21 @@ fi
 # $PTII/ptolemy/apps/makefile if the Java Communications API was found
 
 
+# Set to tini and used in 
+# $PTII/ptolemy/apps/makefile if TINI was found
+
+
 # Set to waba and used in 
 # $PTII/ptolemy/apps/makefile if Waba was found
 
 
 # Location of the PtII directory
+
+
+# tini/bin/tinclasses.jar file used by the Dallas Semi Tini
+
+
+# Directory that contains the Tini installation
 
 
 # waba/tools/classes.jar file used by the PalmOS WABA
@@ -1600,8 +1690,11 @@ s%@PTJAVASOUND_DIR@%$PTJAVASOUND_DIR%g
 s%@PTJSPACES_DIR@%$PTJSPACES_DIR%g
 s%@PTKVM_DIR@%$PTKVM_DIR%g
 s%@PTLEGO_DIR@%$PTLEGO_DIR%g
+s%@PTTINI_DIR@%$PTTINI_DIR%g
 s%@PTWABA_DIR@%$PTWABA_DIR%g
 s%@PTII_DEFAULT@%$PTII_DEFAULT%g
+s%@TINI_CLASSES@%$TINI_CLASSES%g
+s%@TINI_DIR@%$TINI_DIR%g
 s%@WABA_CLASSES@%$WABA_CLASSES%g
 s%@WABA_DIR@%$WABA_DIR%g
 
