configure.in changed

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -907,7 +907,7 @@ Optional Packages:
   --with-waba=DIR       use PalmOS WABA from DIR,
                           defaults to \$PTII/vendors/misc/waba/wabasdk
   --with-X10=DIR       use X10 from DIR,
-                          defaults to \$PTII/vendors/misc/x10
+                              defaults to \$PTII/vendors/misc/x10
 
 Some influential environment variables:
   CC          C compiler command
@@ -7475,8 +7475,8 @@ echo "${ECHO_T}$ANTLR_DIR" >&6
 echo "$as_me: WARNING: Failed to find PTII/ptolemy/actor/ptalon/antlr/antlr.jar
     If it is not present, you will not be able to use the
     Ptalon." >&2;}
-	PTPTALON_DIR=
-	PTPTALON_PACKAGES=
+	# Note that we don't substitute in the ${PTII} here
+	PTPTALON_DIR='${PTII}/ptolemy/actor/ptalon/antlr'
     fi
 
     if test ! "$HAS_GENERICS" = "yes"; then
@@ -8217,7 +8217,17 @@ if test ! -d "$X10_USER_DIR"; then
 echo "${ECHO_T}$X10_USER_DIR is not present,
     so we need not find the X10 SDK. X10 is the power line comm interface." >&6
 else
-    echo "$as_me:$LINENO: checking for X10 directory" >&5
+    if test "$COMMAPI_PRESENT" = "no"; then
+        { echo "$as_me:$LINENO: WARNING: The Java Serial Port Communications API is not installed.
+    The X10 Interface requires the commapi.
+    The commapi can be downloaded from http://java.sun.com/products/javacomm/
+    and placed  in \$PTII/vendors/sun/commapi" >&5
+echo "$as_me: WARNING: The Java Serial Port Communications API is not installed.
+    The X10 Interface requires the commapi.
+    The commapi can be downloaded from http://java.sun.com/products/javacomm/
+    and placed  in \$PTII/vendors/sun/commapi" >&2;}
+    else
+        echo "$as_me:$LINENO: checking for X10 directory" >&5
 echo $ECHO_N "checking for X10 directory... $ECHO_C" >&6
 
 # Check whether --with-x10 or --without-x10 was given.
@@ -8228,25 +8238,13 @@ else
   X10_DIR=$PTII/vendors/misc/x10
 fi;
 
-    if test -d "$X10_DIR"; then
-      	echo "$as_me:$LINENO: result: $X10_DIR" >&5
+        if test -d "$X10_DIR"; then
+	   echo "$as_me:$LINENO: result: $X10_DIR" >&5
 echo "${ECHO_T}$X10_DIR" >&6
-      	echo "$as_me:$LINENO: checking for \$X10_DIR/tjx10p-13/lib/x10.jar" >&5
+           echo "$as_me:$LINENO: checking for \$X10_DIR/tjx10p-13/lib/x10.jar" >&5
 echo $ECHO_N "checking for \$X10_DIR/tjx10p-13/lib/x10.jar... $ECHO_C" >&6
-	if test -f "$X10_DIR/tjx10p-13/lib/x10.jar"; then
-	   X10_CLASSES=${X10_DIR}/tjx10p-13/lib/x10.jar
-	   echo "$as_me:$LINENO: result: $X10_CLASSES" >&5
-echo "${ECHO_T}$X10_CLASSES" >&6
-	   PTX10_DIR=x10
-	   # PTX10_PACKAGES is used in ptII/doc/makefile
-	   PTX10_PACKAGES=ptolemy.actor.lib.x10
-	else
-           echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
-      	   echo "$as_me:$LINENO: checking for \$X10_DIR/tjx10p-12/lib/x10.jar" >&5
-echo $ECHO_N "checking for \$X10_DIR/tjx10p-12/lib/x10.jar... $ECHO_C" >&6
-	   if test -f "$X10_DIR/tjx10p-12/lib/x10.jar"; then
-	       X10_CLASSES=${X10_DIR}/tjx10p-12/lib/x10.jar
+	   if test -f "$X10_DIR/tjx10p-13/lib/x10.jar"; then
+	       X10_CLASSES=${X10_DIR}/tjx10p-13/lib/x10.jar
 	       echo "$as_me:$LINENO: result: $X10_CLASSES" >&5
 echo "${ECHO_T}$X10_CLASSES" >&6
 	       PTX10_DIR=x10
@@ -8255,26 +8253,37 @@ echo "${ECHO_T}$X10_CLASSES" >&6
 	   else
                echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
-	       echo "$as_me:$LINENO: checking for \$X10_DIR/tjx10p-11/lib/x10.jar" >&5
-echo $ECHO_N "checking for \$X10_DIR/tjx10p-11/lib/x10.jar... $ECHO_C" >&6
-	       if test -f "$X10_DIR/tjx10p-11/lib/x10.jar"; then
-	           X10_CLASSES=${X10_DIR}/tjx10p-11/lib/x10.jar
+      	       echo "$as_me:$LINENO: checking for \$X10_DIR/tjx10p-12/lib/x10.jar" >&5
+echo $ECHO_N "checking for \$X10_DIR/tjx10p-12/lib/x10.jar... $ECHO_C" >&6
+	       if test -f "$X10_DIR/tjx10p-12/lib/x10.jar"; then
+	           X10_CLASSES=${X10_DIR}/tjx10p-12/lib/x10.jar
 	           echo "$as_me:$LINENO: result: $X10_CLASSES" >&5
 echo "${ECHO_T}$X10_CLASSES" >&6
 	           PTX10_DIR=x10
-               else
 	           # PTX10_PACKAGES is used in ptII/doc/makefile
-	           PTX10_PACKAGES=
-	           X10_CLASSES=
-	           echo "$as_me:$LINENO: result: no" >&5
+	           PTX10_PACKAGES=ptolemy.actor.lib.x10
+	       else
+                   echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
+	           echo "$as_me:$LINENO: checking for \$X10_DIR/tjx10p-11/lib/x10.jar" >&5
+echo $ECHO_N "checking for \$X10_DIR/tjx10p-11/lib/x10.jar... $ECHO_C" >&6
+	           if test -f "$X10_DIR/tjx10p-11/lib/x10.jar"; then
+	               X10_CLASSES=${X10_DIR}/tjx10p-11/lib/x10.jar
+	               echo "$as_me:$LINENO: result: $X10_CLASSES" >&5
+echo "${ECHO_T}$X10_CLASSES" >&6
+	               PTX10_DIR=x10
+                   else
+	               # PTX10_PACKAGES is used in ptII/doc/makefile
+	               PTX10_PACKAGES=
+	               X10_CLASSES=
+	               echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+                   fi
                fi
-           fi
+            fi
         fi
-    fi
-
-    if test -z "$PTX10_DIR"; then
-        { echo "$as_me:$LINENO: WARNING: Failed to find tjx10p-12/lib/x10.jar
+        if test -z "$PTX10_DIR"; then
+            { echo "$as_me:$LINENO: WARNING: Failed to find tjx10p-12/lib/x10.jar
     or tjx10p-11/lib/x10.jar, perhaps X10 is not installed?
     You need not download X10 unless you plan on building applications
     using the X10 interface.
@@ -8286,13 +8295,14 @@ echo "$as_me: WARNING: Failed to find tjx10p-12/lib/x10.jar
     using the X10 interface.
     The X10 SDK can be downloaded from http://x10.homelinux.org.
     See also $PTII/vendors/misc/x10/README.txt" >&2;}
-	# Note that we don't substitute in the ${PTII} or $(X10_DIR) here
-	X10_DIR='${PTII}/vendors/misc/x10'
-   	X10_CLASSES='${X10_DIR}/tjx10p-12/lib/x10.jar'
-    else
-	# Set to x10 and used in
-	# $PTII/ptolemy/actor/lib/x10/makefile if x10 was found
-	PTX10_DIR=x10
+	    # Note that we don't substitute in the ${PTII} or $(X10_DIR) here
+	    X10_DIR='${PTII}/vendors/misc/x10'
+   	    X10_CLASSES='${X10_DIR}/tjx10p-12/lib/x10.jar'
+        else
+	    # Set to x10 and used in
+	    # $PTII/ptolemy/actor/lib/x10/makefile if x10 was found
+	    PTX10_DIR=x10
+        fi
     fi
 fi
 
@@ -8892,9 +8902,10 @@ for ac_i in : $LIBOBJS; do test "x$ac_i" = x: && continue
   # 1. Remove the extension, and $U if already installed.
   ac_i=`echo "$ac_i" |
 	 sed 's/\$U\././;s/\.o$//;s/\.obj$//'`
-  # 2. Add them.
-  ac_libobjs="$ac_libobjs $ac_i\$U.$ac_objext"
-  ac_ltlibobjs="$ac_ltlibobjs $ac_i"'$U.lo'
+  # 2. Prepend LIBOBJDIR.  When used with automake>=1.10 LIBOBJDIR
+  #    will be set to the directory where LIBOBJS objects are built.
+  ac_libobjs="$ac_libobjs \${LIBOBJDIR}$ac_i\$U.$ac_objext"
+  ac_ltlibobjs="$ac_ltlibobjs \${LIBOBJDIR}$ac_i"'$U.lo'
 done
 LIBOBJS=$ac_libobjs
 
