configure.in changed

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -776,6 +776,9 @@ PTGMP_LD_FLAGS
 PTGMP_LIB
 PTGRDOMAIN_JAR
 PTGR_PACKAGES
+PTHOMER_DIR
+PTHOMER_JARS
+PTHOMER_PACKAGES
 PTII
 PTITEXTPDF_DIR
 PTITEXTPDF_JAR
@@ -1499,6 +1502,12 @@ Optional Packages:
                           defaults to \$PTII/vendors/gc/gc/include
   --with-itextpdf=JARFILE       use iText from JARFILE,
                           defaults to \$PTII/vendors/misc/itext/iText.jar
+  --with-openideutil=JAR       use org-openide-util.jar from JAR,
+                          defaults to \$PTII/lib/org-openide-util.jar
+  --with-openideutillookup=JAR       use org-openide-util-lookup.jar from JAR,
+                          defaults to \$PTII/lib/org-openide-util-lookup.jar
+  --with-netbeansapivisual=JAR       use org-netbeans-api-visual.jar from JAR,
+                              defaults to \$PTII/lib/org-netbeans-api-visual.jar
   --with-javamail=DIRECTORY       use JavaMail interface from DIRECTORY,
                           defaults to \$PTII/vendors/oracle/javamail
   --with-jogl=DIRECTORY       use Java OpenGL interface (jogl) from DIRECTORY,
@@ -7633,6 +7642,105 @@ echo "$as_me: WARNING: Failed to find gmp.h, which is only
 fi
 
 #--------------------------------------------------------------------
+#       $PTII/ptolemy/homer is a gui builder used by HandSimDroid
+#	to allow complex models to be run on handheld devices
+#	http://chess.eecs.berkeley.edu/handsimdroid
+#
+#--------------------------------------------------------------------
+
+# PTHOMER_DIR is set to homer and used in
+# $PTII/ptolemy/makefile if the netbeans visual gui code is found
+PTHOMER_DIR=
+
+# Jar files necessary for compilation of homer
+PTHOMER_JARS=
+
+# We only need to look for Hessian if $HOMER_USER_DIR is present
+HOMER_USER_DIR="$PTII/ptolemy/homer"
+if test ! -d "$HOMER_USER_DIR"; then
+    if test "${PTVERBOSE:-none}" != "none"; then { echo "$as_me:$LINENO: result: $HOMER_USER_DIR is not present,
+    so we need not find the Netbeans visual gui interface." >&5
+echo "${ECHO_T}$HOMER_USER_DIR is not present,
+    so we need not find the Netbeans visual gui interface." >&6; }; fi
+else
+    { echo "$as_me:$LINENO: checking for org-openide-util.jar, used by homer " >&5
+echo $ECHO_N "checking for org-openide-util.jar, used by homer ... $ECHO_C" >&6; }
+
+# Check whether --with-openideutil was given.
+if test "${with_openideutil+set}" = set; then
+  withval=$with_openideutil; PTOPENIDEUTIL_JAR=$withval
+else
+  PTOPENIDEUTIL_JAR=$PTII/lib/org-openide-util.jar
+fi
+
+
+    if test  -f "$PTOPENIDEUTIL_JAR"; then
+	if test "${PTVERBOSE:-none}" = "none"; then { echo "$as_me:$LINENO: result: ok" >&5
+echo "${ECHO_T}ok" >&6; }; else { echo "$as_me:$LINENO: result: $PTOPENIDEUTIL_JAR" >&5
+echo "${ECHO_T}$PTOPENIDEUTIL_JAR" >&6; }; fi
+        { echo "$as_me:$LINENO: checking for org-openide-util-lookup.jar, used by homer " >&5
+echo $ECHO_N "checking for org-openide-util-lookup.jar, used by homer ... $ECHO_C" >&6; }
+
+# Check whether --with-openideutillookup was given.
+if test "${with_openideutillookup+set}" = set; then
+  withval=$with_openideutillookup; PTOPENIDEUTILLOOKUP_JAR=$withval
+else
+  PTOPENIDEUTILLOOKUP_JAR=$PTII/lib/org-openide-util-lookup.jar
+fi
+
+        if test  -f "$PTOPENIDEUTILLOOKUP_JAR"; then
+	    if test "${PTVERBOSE:-none}" = "none"; then { echo "$as_me:$LINENO: result: ok" >&5
+echo "${ECHO_T}ok" >&6; }; else { echo "$as_me:$LINENO: result: $PTOPENIDEUTILLOOKUP_JAR" >&5
+echo "${ECHO_T}$PTOPENIDEUTILLOOKUP_JAR" >&6; }; fi
+            { echo "$as_me:$LINENO: checking for org-netbeans-api-visual.jar, used by homer " >&5
+echo $ECHO_N "checking for org-netbeans-api-visual.jar, used by homer ... $ECHO_C" >&6; }
+
+# Check whether --with-netbeansapivisual was given.
+if test "${with_netbeansapivisual+set}" = set; then
+  withval=$with_netbeansapivisual; PTNETBEANSAPIVISUAL_JAR=$withval
+else
+  PTNETBEANSAPIVISUAL_JAR=$PTII/lib/org-netbeans-api-visual.jar
+fi
+
+            if test  -f "$PTNETBEANSAPIVISUAL_JAR"; then
+	        if test "${PTVERBOSE:-none}" = "none"; then { echo "$as_me:$LINENO: result: ok" >&5
+echo "${ECHO_T}ok" >&6; }; else { echo "$as_me:$LINENO: result: $PTNETBEANSAPIVISUAL_JAR" >&5
+echo "${ECHO_T}$PTNETBEANSAPIVISUAL_JAR" >&6; }; fi
+
+	        # Set to homer and used in $PTII/ptolemy/makefile
+	        PTHOMER_DIR=homer
+                # PTHOMER_PACKAGES is used in ptII/doc/makefile
+		PTHOMER_PACKAGES="ptolemy.homer.events ptolemy.homer.gui ptolemy.homer.tree ptolemy.homer ptolemy.homer.kernel ptolemy.homer.widgets"
+            fi
+        fi
+    fi
+
+    if test "$PTHOMER_DIR" = ""; then
+        { echo "$as_me:$LINENO: WARNING: Failed to find the jar files necessary to compile injection.
+    The injection code interface is used to support Ptolemy running on the Android.
+    For further instructions, see $PTII/ptolemy/actor/injection/package.html " >&5
+echo "$as_me: WARNING: Failed to find the jar files necessary to compile injection.
+    The injection code interface is used to support Ptolemy running on the Android.
+    For further instructions, see $PTII/ptolemy/actor/injection/package.html " >&2;}
+    else
+        PTHOMER_JARS="${PTOPENIDEUTIL_JAR}${CLASSPATHSEPARATOR}${PTOPENIDEUTILLOOKUP_JAR}${CLASSPATHSEPARATOR}${PTNETBEANSAPIVISUAL_JAR}${CLASSPATH}"
+    fi
+fi
+
+if test -z "$PTHOMER_JARS"; then
+   ECLIPSE_EXCLUDING_SRC="$ECLIPSE_EXCLUDING_SRC|ptolemy/homer/"
+else
+   ECLIPSE_CLASSPATHENTRY_LIBS="$ECLIPSE_CLASSPATHENTRY_LIBS \
+       <classpathentry kind=\"lib\" path=\"$PTOPENIDEUTIL_JAR\"/>"
+   ECLIPSE_CLASSPATHENTRY_LIBS="$ECLIPSE_CLASSPATHENTRY_LIBS \
+       <classpathentry kind=\"lib\" path=\"$PTOPENIDEUTILLOOKUP_JAR\"/>"
+   ECLIPSE_CLASSPATHENTRY_LIBS="$ECLIPSE_CLASSPATHENTRY_LIBS \
+       <classpathentry kind=\"lib\" path=\"$PTNETBEANSAPIVISUAL_JAR\"/>"
+fi
+
+
+
+#--------------------------------------------------------------------
 #       JAI is the Java Advanced Imaging Framework
 #	For more information,
 #       see https://jai.dev.java.net/
@@ -12682,6 +12790,15 @@ fi
 # PTGR_PACKAGES is used in ptII/doc/makefile
 
 
+# Set to homer and used in $PTII/ptolemy/makefile if the netbeans visual gui code is found.
+
+
+# Netbeans Jar files necessary for compilation of homer
+
+
+# Ptolemy II packages that use Netbeans gui code
+
+
 # Location of the the PTII directory
 # $PTII/ptolemy/plot/ptplot.jnlp.in reads this
 
@@ -13890,6 +14007,9 @@ PTGMP_LD_FLAGS!$PTGMP_LD_FLAGS$ac_delim
 PTGMP_LIB!$PTGMP_LIB$ac_delim
 PTGRDOMAIN_JAR!$PTGRDOMAIN_JAR$ac_delim
 PTGR_PACKAGES!$PTGR_PACKAGES$ac_delim
+PTHOMER_DIR!$PTHOMER_DIR$ac_delim
+PTHOMER_JARS!$PTHOMER_JARS$ac_delim
+PTHOMER_PACKAGES!$PTHOMER_PACKAGES$ac_delim
 PTII!$PTII$ac_delim
 PTITEXTPDF_DIR!$PTITEXTPDF_DIR$ac_delim
 PTITEXTPDF_JAR!$PTITEXTPDF_JAR$ac_delim
@@ -13919,9 +14039,6 @@ PTJNI_SHAREDLIBRARY_CFLAG!$PTJNI_SHAREDLIBRARY_CFLAG$ac_delim
 PTJNI_SHAREDLIBRARY_LDFLAG!$PTJNI_SHAREDLIBRARY_LDFLAG$ac_delim
 PTJNI_SHAREDLIBRARY_PREFIX!$PTJNI_SHAREDLIBRARY_PREFIX$ac_delim
 PTJNI_SHAREDLIBRARY_SUFFIX!$PTJNI_SHAREDLIBRARY_SUFFIX$ac_delim
-PTJNI_SHAREDLIBRARY_SUFFIX2!$PTJNI_SHAREDLIBRARY_SUFFIX2$ac_delim
-PTJNI_LIBRARIES!$PTJNI_LIBRARIES$ac_delim
-PTJOGL_DIR!$PTJOGL_DIR$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -13963,6 +14080,9 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+PTJNI_SHAREDLIBRARY_SUFFIX2!$PTJNI_SHAREDLIBRARY_SUFFIX2$ac_delim
+PTJNI_LIBRARIES!$PTJNI_LIBRARIES$ac_delim
+PTJOGL_DIR!$PTJOGL_DIR$ac_delim
 PTJOGL_JARS!$PTJOGL_JARS$ac_delim
 PTJOGL_PACKAGES!$PTJOGL_PACKAGES$ac_delim
 PTJOYSTICK_DIR!$PTJOYSTICK_DIR$ac_delim
@@ -14037,7 +14157,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 72; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 75; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
