configure.in changed

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -310,7 +310,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS CMD_PATH FIND JAVAC JAVA CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CPP EGREP PTECLIPSE PTCC CXX CXXFLAGS ac_ct_CXX JJTREE MATLAB PTMATLAB_CC CALTROP_DIR CHIC_DIR CLASSPATHSEPARATOR COLT_DIR CMKIT_DIR COMMAPI_DIR COMMAPI_PRESENT ECLIPSE_DIR GC_INCLUDE_DIR GC_LD_DIRECTIVE ECLIPSE_EXCLUDING_SRC ECLIPSE_CLASSPATHENTRY_LIBS IMAGEJ_JAR JAI_JARS JAR_INDEX JAVA_SYSTEM_JAR JAVACC JAVACC_DIR JAVAX_CRYPTO_JAR JDOCBREAKITERATOR JDOCTAGLET JHDL_JAR JINI_DIR JINI_PRESENT JOYSTICK_JAR JTCLSH JTREE JVERSION JMF_JARS JODE_CLASSES JYTHON_DIR JXTA_DIR KVM_CLASSES KVM_DIR LEJOS_DIR MAJOR_OS_NAME MATLAB_DIR MATLAB_LIBDIR PSDF_DIR PTBACKTRACK_ECLIPSE_DIR PTBACKTRACK_ECLIPSE_DOC_JARS PTBACKTRACK_ECLIPSE_JARS PTBACKTRACK_ECLIPSE_PACKAGES PTBOOST_INCLUDE PTCALTROP_DIR PTCHIC_DIR PTCM_DIR PTCOLT_DIR PTCOLT_JARS PTCOLT_PACKAGES PTCOMM_DIR PTCOMM_PACKAGES PTCOPERNICUS_DIR PTDISTRIBUTED_DIR PTDISTRIBUTED_JARS PTDISTRIBUTED_PACKAGES PTDOCLETS_DIR PTGMP_INCLUDE PTGMP_LD_FLAGS PTGMP_LIB PTGRDOMAIN_JAR PTGR_PACKAGES PTII PTJACL_DIR PTJACL_JAR PTJAI_DIR PTJAI_PACKAGES PTJAVA_DIR PTJAVA_DIR_NO_CYGDRIVE PTJAVA_HOME PTJAVA3D_DIR PTJHDL_DIR PTJMF_DIR PTJMF_PACKAGES PTJNI_DIR PTJNI_ARCHITECTURE PTJNI_DL_LIBRARY PTJNI_LIB_ARCHITECTURE PTJNI_NO_CYGWIN PTJNI_SHAREDLIBRARY_CFLAG PTJNI_SHAREDLIBRARY_LDFLAG PTJNI_SHAREDLIBRARY_PREFIX PTJNI_SHAREDLIBRARY_SUFFIX PTJNI_LIBRARIES PTJOYSTICK_DIR PTJOYSTICK_PACKAGES PTJYTHON_DIR PTJXTA_DIR PTKVM_DIR PTLEGO_DIR PTLEJOS_DIR PTMATLAB_DIR PTMATLAB_LD_ARGS PTMESCAL_DIR PTPSDF_DIR PTSVG_DIR PTSVG_JAR PTQUICKTIME_DIR PTQUICKTIME_PACKAGES PTTINI_DIR PTTINYOS_DIR PTGIOTTO_DIR PTVR_DIR PTVR_JAR PTVR_PACKAGES PTWABA_DIR PTX10_DIR PTX10_PACKAGES PTII_LOCALURL QTJAVA_ZIP SOOT_CLASSES SOOT_DIR TINI_CLASSES TINI_DIR TOOLS_JAR TOSROOT_NO_CYGDRIVE TOSDIR_NO_CYGDRIVE GIOTTO_CLASSES GIOTTO_DIR WABA_CLASSES WABA_DIR X10_CLASSES X10_DIR LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS CMD_PATH FIND JAVAC JAVA CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CPP EGREP PTECLIPSE PTCC CXX CXXFLAGS ac_ct_CXX JJTREE MATLAB PTMATLAB_CC CALTROP_DIR CHIC_DIR CLASSPATHSEPARATOR COLT_DIR CMKIT_DIR COMMAPI_DIR COMMAPI_PRESENT ECLIPSE_DIR GC_INCLUDE_DIR GC_LD_DIRECTIVE ECLIPSE_EXCLUDING_SRC ECLIPSE_CLASSPATHENTRY_LIBS IMAGEJ_JAR JAI_JARS JAR_INDEX JAVA_SYSTEM_JAR JAVACC JAVACC_DIR JAVAX_CRYPTO_JAR JDOCBREAKITERATOR JDOCTAGLET JHDL_JAR JINI_DIR JINI_PRESENT JOYSTICK_JAR JTCLSH JTREE JVERSION JMF_JARS JODE_CLASSES JYTHON_DIR JXTA_DIR KVM_CLASSES KVM_DIR LEJOS_DIR MAJOR_OS_NAME MATLAB_DIR MATLAB_LIBDIR PSDF_DIR PTBACKTRACK_ECLIPSE_DIR PTBACKTRACK_ECLIPSE_DOC_JARS PTBACKTRACK_ECLIPSE_JARS PTBACKTRACK_ECLIPSE_PACKAGES PTBOOST_INCLUDE PTCALTROP_DIR PTCHIC_DIR PTCM_DIR PTCOLT_DIR PTCOLT_JARS PTCOLT_PACKAGES PTCOMM_DIR PTCOMM_PACKAGES PTCOPERNICUS_DIR PTDISTRIBUTED_DIR PTDISTRIBUTED_JARS PTDISTRIBUTED_PACKAGES PTDOCLETS_DIR PTGMP_INCLUDE PTGMP_LD_FLAGS PTGMP_LIB PTGRDOMAIN_JAR PTGR_PACKAGES PTII PTJACL_DIR PTJACL_JAR PTJAI_DIR PTJAI_PACKAGES PTJAVA_DIR PTJAVA_DIR_NO_CYGDRIVE PTJAVA_HOME PTJAVA3D_DIR PTJHDL_DIR PTJMF_DIR PTJMF_PACKAGES PTJNI_DIR PTJNI_ARCHITECTURE PTJNI_DL_LIBRARY PTJNI_LIB_ARCHITECTURE PTJNI_NO_CYGWIN PTJNI_SHAREDLIBRARY_CFLAG PTJNI_SHAREDLIBRARY_LDFLAG PTJNI_SHAREDLIBRARY_PREFIX PTJNI_SHAREDLIBRARY_SUFFIX PTJNI_LIBRARIES PTJOYSTICK_DIR PTJOYSTICK_PACKAGES PTJYTHON_DIR PTJXTA_DIR PTKVM_DIR PTLEGO_DIR PTLEJOS_DIR PTMATLAB_DIR PTMATLAB_LD_ARGS PTMESCAL_DIR PTPSDF_DIR PTSVG_DIR PTSVG_JAR PTPTALON_DIR ANTLR_DIR PTQUICKTIME_DIR PTQUICKTIME_PACKAGES PTTINI_DIR PTTINYOS_DIR PTGIOTTO_DIR PTVR_DIR PTVR_JAR PTVR_PACKAGES PTWABA_DIR PTX10_DIR PTX10_PACKAGES PTII_LOCALURL QTJAVA_ZIP SOOT_CLASSES SOOT_DIR TINI_CLASSES TINI_DIR TOOLS_JAR TOSROOT_NO_CYGDRIVE TOSDIR_NO_CYGDRIVE GIOTTO_CLASSES GIOTTO_DIR WABA_CLASSES WABA_DIR X10_CLASSES X10_DIR LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -892,6 +892,8 @@ Optional Packages:
                           defaults to \$PTII/vendors/sun/j2me_cldc
   --with-mapss=DIR       use mapss.jar from DIR,
                           defaults to \$PTII/lib
+  --with-antlr=DIR       use antlr.jar from DIR,
+                          defaults to \$PTII/ptolemy/actor/ptalon/antlr'
   --with-soot=DIR       use SOOT from DIR,
                           defaults to \$PTII/lib
   --with-javasystemjar=DIR       use rt.lib from DIR,
@@ -7382,6 +7384,59 @@ else
 fi
 
 #--------------------------------------------------------------------
+#       Ptalon
+#--------------------------------------------------------------------
+
+# PTPTALON_DIR is set to ptalon and used in
+# $PTII/ptolemy/actor/makefile if antlr.jar was found.
+PTPTALON_DIR=
+
+# Directory that contains the antlr.jar file
+ANTLR_DIR='${PTII}/ptolemy/actor/ptalon/antlr'
+
+# We only need to look for on if $PTII/ptolemy/actor/ptalon exists
+PTALON_USER_DIR="$PTII/ptolemy/actor/ptalon"
+if test ! -d "$PTALON_USER_DIR"; then
+    echo "$as_me:$LINENO: result: $PTALON_USER_DIR is not present,
+    so we need not find anltr.jar." >&5
+echo "${ECHO_T}$PTALON_USER_DIR is not present,
+    so we need not find anltr.jar." >&6
+else
+    echo "$as_me:$LINENO: checking for anltr.jar, used by the Ptalon" >&5
+echo $ECHO_N "checking for anltr.jar, used by the Ptalon... $ECHO_C" >&6
+
+# Check whether --with-mapss or --without-mapss was given.
+if test "${with_mapss+set}" = set; then
+  withval="$with_mapss"
+  ANTLR_DIR=$withval
+else
+  ANTLR_DIR=$PTII/ptolemy/actor/ptalon/antlr
+fi;
+
+    if test -f "$ANTLR_DIR/antlr.jar"; then
+	echo "$as_me:$LINENO: result: $ANTLR_DIR" >&5
+echo "${ECHO_T}$ANTLR_DIR" >&6
+	PTPTALON_DIR=ptalon
+    else
+        { echo "$as_me:$LINENO: WARNING: Failed to find PTII/ptolemy/actor/ptalon/antlr/antlr.jar
+    If it is not present, you will not be able to use the
+    Ptalon." >&5
+echo "$as_me: WARNING: Failed to find PTII/ptolemy/actor/ptalon/antlr/antlr.jar
+    If it is not present, you will not be able to use the
+    Ptalon." >&2;}
+	# Note that we don't substitute in the ${PTII} here
+	PTALON_DIR='${PTII}/ptolemy/actor/ptalon/antlr'
+    fi
+fi
+
+if test -z "$PTALON_DIR"; then
+   ECLIPSE_EXCLUDING_SRC="$ECLIPSE_EXCLUDING_SRC|ptolemy/antlr/ptalon/"
+else
+   ECLIPSE_CLASSPATHENTRY_LIBS="$ECLIPSE_CLASSPATHENTRY_LIBS \
+    <classpathentry kind=\"lib\" path=\"$ANTLR_DIR/antlr.jar\"/> "
+fi
+
+#--------------------------------------------------------------------
 #	Test for quicktime
 #--------------------------------------------------------------------
 # PTQUICKTIME_DIR is set to quicktime and used in
@@ -8500,6 +8555,13 @@ fi
 # Jar file used by diva/util/java2d/svg/makefile
 
 
+# PTPTALON_DIR is set to ptalon and used in
+# $PTII/ptolemy/actor/makefile if antlr.jar was found.
+
+
+# Directory that contains the antlr.jar file, used by ptalon
+
+
 # Set to quicktime and used in $PTII/ptolemy/domains/gr/lib/makefile if
 # QuickTime for Java was found.
 
@@ -9355,6 +9417,8 @@ s,@PTMESCAL_DIR@,$PTMESCAL_DIR,;t t
 s,@PTPSDF_DIR@,$PTPSDF_DIR,;t t
 s,@PTSVG_DIR@,$PTSVG_DIR,;t t
 s,@PTSVG_JAR@,$PTSVG_JAR,;t t
+s,@PTPTALON_DIR@,$PTPTALON_DIR,;t t
+s,@ANTLR_DIR@,$ANTLR_DIR,;t t
 s,@PTQUICKTIME_DIR@,$PTQUICKTIME_DIR,;t t
 s,@PTQUICKTIME_PACKAGES@,$PTQUICKTIME_PACKAGES,;t t
 s,@PTTINI_DIR@,$PTTINI_DIR,;t t
