configure.in changed

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1089,6 +1089,39 @@ echo "configure:1074: checking for how to run jacl" >&5
 fi
 
 #--------------------------------------------------------------------
+#	Test for javax.media.j3d (Java 3D)
+#--------------------------------------------------------------------
+# PTJAVA3D_DIR is set to dd3d and used in 
+# $PTII/ptolemy/actor/lib/makefile if Java 3D was found
+PTJAVA3D_DIR=
+# We only need to look for Java3D if the dd3d demo is present
+JAVA3D_USER_DIR="$PTII/ptolemy/domains/dd3d"
+
+if test ! -d "$JAVA3D_USER_DIR"; then
+    echo "$ac_t""$JAVA3D_USER_DIR
+  is not present, so we need not find Java 3D" 1>&6
+else
+    echo $ac_n "checking for Java 3D""... $ac_c" 1>&6
+echo "configure:1106: checking for Java 3D" >&5
+    # We need to run javac in the config directory so that javac from jdk1.1.6
+    # under NT and cygwin works properly
+    startdir=`pwd`
+    cd $srcdir/config
+    # Don't use 'env $JAVAC . . .' here, it will not work under Cygwin
+    if $JAVAC java3dTest.java ; then
+       echo "$ac_t""ok" 1>&6
+       PTJAVA3D_DIR=dd3d 
+    else
+       echo "configure: warning: '$JAVAC java3dTest.java' failed.
+       http://java.sun.com/products/java-media/3D/download.html
+       Java 3D is only needed if you want to build in
+       $JAVA3D_USER_DIR,
+       otherwise the build will proceed fine with out Java 3D." 1>&2
+    fi
+fi
+cd $startdir
+
+#--------------------------------------------------------------------
 #	Test for javax.sound
 #--------------------------------------------------------------------
 # PTJAVASOUND_DIR is set to javasound and used in 
@@ -1096,7 +1129,7 @@ fi
 PTJAVASOUND_DIR=
 
 echo $ac_n "checking for javax.sound""... $ac_c" 1>&6
-echo "configure:1100: checking for javax.sound" >&5
+echo "configure:1133: checking for javax.sound" >&5
 # We need to run javac in the config directory so that javac from jdk1.1.6
 # under NT and cygwin works properly
 startdir=`pwd`
@@ -1133,7 +1166,7 @@ if test ! -d "$JINI_USER_DIR"; then
     JINI_DIR='\$PTII/vendors/sun/jini/jini1_0_1'
 else
     echo $ac_n "checking for jini directory""... $ac_c" 1>&6
-echo "configure:1137: checking for jini directory" >&5
+echo "configure:1170: checking for jini directory" >&5
     # Check whether --with-jini or --without-jini was given.
 if test "${with_jini+set}" = set; then
   withval="$with_jini"
@@ -1184,7 +1217,7 @@ find the PalmOS kvm" 1>&6
     KVM_CLASSES='$(KVM_DIR)/bin/api/classes'
 else
     echo $ac_n "checking for kvm directory""... $ac_c" 1>&6
-echo "configure:1188: checking for kvm directory" >&5
+echo "configure:1221: checking for kvm directory" >&5
     # Check whether --with-kvm or --without-kvm was given.
 if test "${with_kvm+set}" = set; then
   withval="$with_kvm"
@@ -1197,7 +1230,7 @@ fi
     if test -d "$KVM_DIR"; then
 	echo "$ac_t""$KVM_DIR" 1>&6
         echo $ac_n "checking for \$KVM_DIR/bin/api/classes""... $ac_c" 1>&6
-echo "configure:1201: checking for \$KVM_DIR/bin/api/classes" >&5
+echo "configure:1234: checking for \$KVM_DIR/bin/api/classes" >&5
 	if test -d "$KVM_DIR/bin/api/classes"; then
 	    KVM_CLASSES='$(KVM_DIR)/bin/api/classes'
 	    echo "$ac_t""$KVM_CLASSES" 1>&6
@@ -1207,13 +1240,13 @@ echo "configure:1201: checking for \$KVM_DIR/bin/api/classes" >&5
     else    
 	echo "$ac_t""Not found in $KVM_DIR" 1>&6
 	echo $ac_n "checking for kvm directory in /j2me_cldc""... $ac_c" 1>&6
-echo "configure:1211: checking for kvm directory in /j2me_cldc" >&5
+echo "configure:1244: checking for kvm directory in /j2me_cldc" >&5
 	# Likely place for kvm under windows
 	KVM_DIR=/j2me_cldc
         if test -d "$KVM_DIR"; then
 	    echo "$ac_t""$KVM_DIR" 1>&6
             echo $ac_n "checking for \$KVM_DIR/bin/api/classes""... $ac_c" 1>&6
-echo "configure:1217: checking for \$KVM_DIR/bin/api/classes" >&5
+echo "configure:1250: checking for \$KVM_DIR/bin/api/classes" >&5
 	    if test -d "$KVM_DIR/bin/api/classes"; then
 	        KVM_CLASSES='$(KVM_DIR)/bin/api/classes'
 	        echo "$ac_t""$KVM_CLASSES" 1>&6
@@ -1262,7 +1295,7 @@ find the PalmOS waba" 1>&6
     WABA_CLASSES='$(WABA_DIR)/classes'
 else
     echo $ac_n "checking for waba directory""... $ac_c" 1>&6
-echo "configure:1266: checking for waba directory" >&5
+echo "configure:1299: checking for waba directory" >&5
     # Check whether --with-waba or --without-waba was given.
 if test "${with_waba+set}" = set; then
   withval="$with_waba"
@@ -1275,7 +1308,7 @@ fi
     if test -d "$WABA_DIR"; then
 	echo "$ac_t""$WABA_DIR" 1>&6
         echo $ac_n "checking for \$WABA_DIR/classes""... $ac_c" 1>&6
-echo "configure:1279: checking for \$WABA_DIR/classes" >&5
+echo "configure:1312: checking for \$WABA_DIR/classes" >&5
 	if test -d "$WABA_DIR/classes"; then
 	    WABA_CLASSES='$(WABA_DIR)/classes'
 	    echo "$ac_t""$WABA_CLASSES" 1>&6
@@ -1285,13 +1318,13 @@ echo "configure:1279: checking for \$WABA_DIR/classes" >&5
     else    
 	echo "$ac_t""Not found in $WABA_DIR" 1>&6
 	echo $ac_n "checking for waba directory in /waba""... $ac_c" 1>&6
-echo "configure:1289: checking for waba directory in /waba" >&5
+echo "configure:1322: checking for waba directory in /waba" >&5
 	# Likely place for waba under windows
 	WABA_DIR=/waba/wabasdk
         if test -d "$WABA_DIR"; then
 	    echo "$ac_t""$WABA_DIR" 1>&6
             echo $ac_n "checking for \$WABA_DIR/classes""... $ac_c" 1>&6
-echo "configure:1295: checking for \$WABA_DIR/classes" >&5
+echo "configure:1328: checking for \$WABA_DIR/classes" >&5
 	    if test -d "$WABA_DIR/classes"; then
 	        WABA_CLASSES='$(WABA_DIR)/classes'
 	        echo "$ac_t""$WABA_CLASSES" 1>&6
@@ -1364,6 +1397,10 @@ fi
 
 
 # Location of the JDK
+
+
+# Set to dd3d and used in 
+# $PTII/ptolemy/domains/makefile if Java 3D was found
 
 
 # Set to javasound and used in 
@@ -1558,6 +1595,7 @@ s%@KVM_DIR@%$KVM_DIR%g
 s%@PTJACL_JAR@%$PTJACL_JAR%g
 s%@PTJACL_JFLAG@%$PTJACL_JFLAG%g
 s%@PTJAVA_DIR@%$PTJAVA_DIR%g
+s%@PTJAVA3D_DIR@%$PTJAVA3D_DIR%g
 s%@PTJAVASOUND_DIR@%$PTJAVASOUND_DIR%g
 s%@PTJSPACES_DIR@%$PTJSPACES_DIR%g
 s%@PTKVM_DIR@%$PTKVM_DIR%g
