configure.in changed, so configure changes

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -20,7 +20,7 @@ ac_help="$ac_help
   --with-javacc=DIR       use JavaCC.zip from DIR,
                            defaults to \$PTOLEMY/vendors/sun/JavaCC"
 ac_help="$ac_help
-  --with-jtclsh=SCRIPT    jtclsh is at BINARY. jtclsh is
+  --with-jtclsh=SCRIPT    tclsh is atY. jtclsh is
                            used for running the test scripts"
 
 # Initialize some variables set by options.
@@ -799,9 +799,9 @@ echo "$ac_t""'$CLASSPATHSEPARATOR'" 1>&6
 
 echo $ac_n "checking for JavaCC""... $ac_c" 1>&6
 echo "configure:802: checking for JavaCC" >&5
-# Check whether --with-java or --without-java was given.
-if test "${with_java+set}" = set; then
-  withval="$with_java"
+# Check whether --with-javacc or --without-javacc was given.
+if test "${with_javacc+set}" = set; then
+  withval="$with_javacc"
   JAVACC_DIR=$withval
 else
   JAVACC_DIR=$PTOLEMY/vendors/sun/JavaCC
@@ -889,9 +889,9 @@ fi
 #	See if there was a command-line option for where Tcl Blend is
 #--------------------------------------------------------------------
 
-# Check whether --with-java or --without-java was given.
-if test "${with_java+set}" = set; then
-  withval="$with_java"
+# Check whether --with-jtclsh or --without-jtclsh was given.
+if test "${with_jtclsh+set}" = set; then
+  withval="$with_jtclsh"
   JTCLSH=$withval
 else
   JTCLSH=jtclsh
@@ -900,7 +900,7 @@ fi
 if test "$JTCLSH" != "jtclsh"; then
     echo $ac_n "checking for jtclsh""... $ac_c" 1>&6
 echo "configure:903: checking for jtclsh" >&5
-    echo "$ac_t""$JTCLSH]" 1>&6;
+    echo "$ac_t""$JTCLSH" 1>&6;
 else
     # Extract the first word of "jtclsh", so it can be a program name with args.
 set dummy jtclsh; ac_word=$2
@@ -934,10 +934,53 @@ else
 fi
 
     if test ! -x "$JTCLSH"; then	
-	echo "configure: warning: jtclsh not found.  jtclsh is a startup script for
-Tcl Blend, which is used to run the test suite.
-You only need to have jtclsh if you are planning on running the test suite.
+	echo "configure: warning: jtclsh not found, so we'll look for tclsh.
+jtclsh is a startup script for Tcl Blend, which is used to run the test suite.
+You only need to have jtclsh or tclsh if you are planning on running
+the test suite.
 See http://www.scriptics.com/java for Tcl Blend sources and binaries." 1>&2
+	for ac_prog in "tclsh80 tclsh8.0 tclsh"
+do
+# Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
+echo "configure:948: checking for $ac_word" >&5
+if eval "test \"`echo '$''{'ac_cv_path_TCLSH'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  case "$TCLSH" in
+  /*)
+  ac_cv_path_TCLSH="$TCLSH" # Let the user override the test with a path.
+  ;;
+  *)
+  IFS="${IFS= 	}"; ac_save_ifs="$IFS"; IFS="${IFS}:"
+  for ac_dir in $PATH; do
+    test -z "$ac_dir" && ac_dir=.
+    if test -f $ac_dir/$ac_word; then
+      ac_cv_path_TCLSH="$ac_dir/$ac_word"
+      break
+    fi
+  done
+  IFS="$ac_save_ifs"
+  ;;
+esac
+fi
+TCLSH="$ac_cv_path_TCLSH"
+if test -n "$TCLSH"; then
+  echo "$ac_t""$TCLSH" 1>&6
+else
+  echo "$ac_t""no" 1>&6
+fi
+
+test -n "$TCLSH" && break
+done
+test -n "$TCLSH" || TCLSH="tclsh"
+
+        if test ! -x "$TCLSH"; then	
+		echo "configure: warning: tclsh80 not found either, so we default to '$TCLSH'.
+tclsh is only necessary for the test suite." 1>&2;
+	fi
+	JTCLSH=$TCLSH
    fi     
 fi 
 
@@ -1115,6 +1158,7 @@ s%@JAVAC@%$JAVAC%g
 s%@JAVA@%$JAVA%g
 s%@JJTREE@%$JJTREE%g
 s%@JTCLSH@%$JTCLSH%g
+s%@TCLSH@%$TCLSH%g
 s%@CLASSPATHSEPARATOR@%$CLASSPATHSEPARATOR%g
 s%@JAVACC@%$JAVACC%g
 s%@JAVACC_DIR@%$JAVACC_DIR%g
