configure.in changed

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -658,6 +658,7 @@ JAVAC
 JAVA
 JAR
 JARSIGNER
+JAVAWS
 KEYTOOL
 CC
 CFLAGS
@@ -3202,6 +3203,79 @@ if test ! -x "$JARSIGNER"; then
        This is only a problem when testing the security actors." >&5
 echo "$as_me: WARNING: The jarsigner command \"$JARSIGNER\" is not executable or not found.
        This is only a problem when testing the security actors." >&2;}
+fi
+
+#
+# The javaws command is used to test Webstart JNLP files.
+#
+{ echo "$as_me:$LINENO: checking for the javaws command" >&5
+echo $ECHO_N "checking for the javaws command... $ECHO_C" >&6; }
+if test -f "$PTJAVA_DIR/bin/javaws"; then
+    if test "${PTVERBOSE:-none}" = "none"; then { echo "$as_me:$LINENO: result: ok" >&5
+echo "${ECHO_T}ok" >&6; }; else { echo "$as_me:$LINENO: result: $PTJAVA_DIR/bin/javaws" >&5
+echo "${ECHO_T}$PTJAVA_DIR/bin/javaws" >&6; }; fi
+    JAVAWS="$PTJAVA_DIR/bin/javaws"
+else
+   if test -f "$PTJAVA_DIR/Commands/java"; then
+       if test "${PTVERBOSE:-none}" = "none"; then { echo "$as_me:$LINENO: result: ok" >&5
+echo "${ECHO_T}ok" >&6; }; else { echo "$as_me:$LINENO: result: $PTJAVA_DIR/Commands/java" >&5
+echo "${ECHO_T}$PTJAVA_DIR/Commands/java" >&6; }; fi
+       JAVAWS="$PTJAVA_DIR/Commands/javaws"
+   else
+       { echo "$as_me:$LINENO: WARNING: Cannot find '$PTJAVA_DIR/bin/javaws'.
+       or '$PTJAVA/Commands/javaws', looking in the path.
+       This is only a problem when testing the Java Webstart (JNLP) files." >&5
+echo "$as_me: WARNING: Cannot find '$PTJAVA_DIR/bin/javaws'.
+       or '$PTJAVA/Commands/javaws', looking in the path.
+       This is only a problem when testing the Java Webstart (JNLP) files." >&2;}
+       # Extract the first word of "javaws", so it can be a program name with args.
+set dummy javaws; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_path_JAVAWS+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $JAVAWS in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_JAVAWS="$JAVAWS" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_path_JAVAWS="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+  ;;
+esac
+fi
+JAVAWS=$ac_cv_path_JAVAWS
+if test -n "$JAVAWS"; then
+  { echo "$as_me:$LINENO: result: $JAVAWS" >&5
+echo "${ECHO_T}$JAVAWS" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
+   fi
+fi
+
+if test ! -x "$JAVAWS"; then
+     { echo "$as_me:$LINENO: WARNING: The javaws command \"$JAVAWS\" is not executable or not found.
+    This is only a problem when testing the Java Webstart (JNLP) files." >&5
+echo "$as_me: WARNING: The javaws command \"$JAVAWS\" is not executable or not found.
+    This is only a problem when testing the Java Webstart (JNLP) files." >&2;}
 fi
 
 #
@@ -10272,6 +10346,9 @@ fi
 # The javadoc binary, used to create html documentation of java classes.
 
 
+# The javaws command is used to test Webstart JNLP files.
+
+
 # Location of jce.jar, usually $(PTJAVA_HOME)/lib/jce.jar
 # Java 1.5 has javax.crypto.Cipher in jce.jar
 # However, we have to be careful of backslashes and /cygwin
@@ -11435,6 +11512,7 @@ JAVAC!$JAVAC$ac_delim
 JAVA!$JAVA$ac_delim
 JAR!$JAR$ac_delim
 JARSIGNER!$JARSIGNER$ac_delim
+JAVAWS!$JAVAWS$ac_delim
 KEYTOOL!$KEYTOOL$ac_delim
 CC!$CC$ac_delim
 CFLAGS!$CFLAGS$ac_delim
@@ -11487,7 +11565,6 @@ JTREE!$JTREE$ac_delim
 JVERSION!$JVERSION$ac_delim
 JMF_JARS!$JMF_JARS$ac_delim
 JODE_CLASSES!$JODE_CLASSES$ac_delim
-JYTHON_DIR!$JYTHON_DIR$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -11529,6 +11606,7 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+JYTHON_DIR!$JYTHON_DIR$ac_delim
 JXTA_DIR!$JXTA_DIR$ac_delim
 KVM_CLASSES!$KVM_CLASSES$ac_delim
 KVM_DIR!$KVM_DIR$ac_delim
@@ -11625,7 +11703,6 @@ PTVR_DIR!$PTVR_DIR$ac_delim
 PTVR_JAR!$PTVR_JAR$ac_delim
 PTVR_PACKAGES!$PTVR_PACKAGES$ac_delim
 PTWABA_DIR!$PTWABA_DIR$ac_delim
-PTX10_DIR!$PTX10_DIR$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -11667,6 +11744,7 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+PTX10_DIR!$PTX10_DIR$ac_delim
 PTX10_PACKAGES!$PTX10_PACKAGES$ac_delim
 PTII_LOCALURL!$PTII_LOCALURL$ac_delim
 QTJAVA_ZIP!$QTJAVA_ZIP$ac_delim
@@ -11689,7 +11767,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 20; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 21; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
