Look for dbxml shared libraries necessary to run the tests

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -310,7 +310,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS CMD_PATH FIND GAWK JAVAC JAVA JAR JARSIGNER JAVAWS KEYTOOL CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CPP EGREP JAVADOC PTECLIPSE PTCC CXX CXXFLAGS ac_ct_CXX PTJYTHON PTJYTHON_BAT JJTREE PTCCJNI JAVAH MATLAB PTMATLAB_CC CALTROP_DIR CHIC_DIR CLASSPATHSEPARATOR COLT_DIR CMKIT_DIR ECLIPSE_CLASSPATHENTRY_PDE_REQUIREDPLUGINS ECLIPSE_DIR GC_INCLUDE_DIR GC_LD_DIRECTIVE ECLIPSE_EXCLUDING_SRC ECLIPSE_CLASSPATHENTRY_LIBS IMAGEJ_JAR JAI_JARS JAR_INDEX JAVA_SYSTEM_JAR JAVACC JAVACC_DIR JAVACV_JAR JAVAX_CRYPTO_JAR JDOCBREAKITERATOR JDOCSOURCEFLAGS JDOCTAG JDOCTAGLET JINI_DIR JINI_PRESENT JOYSTICK_JAR JTCLSH JTREE JVERSION JMF_JARS JNA_JAR JODE_CLASSES JUNIT_JAR JYTHON_DIR JXTA_DIR KIELER_JAR KVM_CLASSES KVM_DIR LEJOS_DIR LIBEXPAT_INCLUDE_DIR LIBEXPAT_LIB_DIR MAJOR_OS_NAME MATLAB_DIR MATLAB_LIBDIR MATLAB_64LIBDIR MYSQL_JAR OPENCV_JAR ORACLE_OJDBC_JAR PSDF_DIR PTBACKTRACK_DIR PTBACKTRACK_ECLIPSE_DIR PTBACKTRACK_ECLIPSE_DOC_JARS PTBACKTRACK_ECLIPSE_JARS PTBACKTRACK_ECLIPSE_PACKAGES PTBOOST_INCLUDE PTBSH_JAR PTBSH_MLC_DIR PTBSH_RUN_DIR PTBSH_PACKAGES PTCALTROP_DIR PTCHIC_DIR PTCM_DIR PTCODEGEN_OPTIONAL_PACKAGES PTCOLT_DIR PTCOLT_JARS PTCOLT_PACKAGES PTCOMM_DIR PTCOMM_PACKAGES PTCOPERNICUS_DIR PTCUNIT_DIR PTDATABASE_DIR PTDATABASE_JNLP_JARS PTDATABASE_PACKAGES PTDB_DIR PTDB_PACKAGES PTDBXML_JARS PTDISTRIBUTED_DIR PTDISTRIBUTED_JARS PTDISTRIBUTED_PACKAGES PTDOCLETS_DIR PTEXCEL_DIR PTEXCEL_PACKAGES PTFUZZY_DIR PTFUZZYENGINE_DIR PTFUZZY_PACKAGES PTGMP_INCLUDE PTGMP_LD_FLAGS PTGMP_LIB PTGRDOMAIN_JAR PTGR_PACKAGES PTGRO_DIR PTGRO_PACKAGES PTII PTITEXTPDF_DIR PTITEXTPDF_JAR PTITEXTPDF_PACKAGES PTJACL_DIR PTJACL_JAR PTJAI_DIR PTJAI_PACKAGES PTJAVACV_DIR PTJAVACV_PACKAGES PTJAVA_DIR PTJAVA_DIR_NO_CYGDRIVE PTJAVA_HOME PTJAVA3D_DIR PTJMF_DIR PTJMF_PACKAGES PTJNI_ARCHITECTURE PTJNI_INCLUDE PTJNI_DL_LIBRARY PTJNI_LIB_ARCHITECTURE PTJNI_NO_CYGWIN PTJNI_GCC_SHARED_FLAG PTJNI_SHAREDLIBRARY_CFLAG PTJNI_SHAREDLIBRARY_LDFLAG PTJNI_SHAREDLIBRARY_PREFIX PTJNI_SHAREDLIBRARY_SUFFIX PTJNI_LIBRARIES PTJOGL_DIR PTJOGL_JARS PTJOYSTICK_DIR PTJOYSTICK_PACKAGES PTJUNIT_PACKAGES PTJXL_JAR PTJYTHON_DIR PTJYTHON_PACKAGES PTJXTA_DIR PTOPENCV_DIR PTOPENCVCG_DIR PTOPENCV_INCLUDE_DIR PTOPENCV_PACKAGES PTKIELER_DIR PTKVM_DIR PTLBNL_DIR PTLEGO_DIR PTLEJOS_DIR PTLIBEXPAT_DIR PTMATLAB_CC_FLAGS PTMATLAB_DIR PTMATLAB_LD_ARGS PTMATLAB_64LD_ARGS PTMESCAL_DIR PTPDFRENDERER_DIR PTPDFRENDERER_JAR PTPSDF_DIR PTSVG_DIR PTSVG_JAR PTPOWERMOCK_DIR PTPOWERMOCK_JARS PTPROCESSING_JARS PTPTALON_DIR PTPTALON_PACKAGES ANTLR_DIR PTQUICKTIME_DIR PTQUICKTIME_PACKAGES PTRXTX_PACKAGES PTSPACE_DIR PTSPACEDOMAIN_JAR PTSPACEDOMAIN_PACKAGES PTTINI_DIR PTTINYOS_DIR PTGIOTTO_DIR PTWABA_DIR PTX10_DIR PTX10_PACKAGES PTII_LOCALURL QTJAVA_ZIP RXTX_JAR RXTX_PRESENT SOOT_CLASSES SOOT_DIR TINI_CLASSES TINI_DIR TOOLS_JAR TOSROOT_NO_CYGDRIVE TOSDIR_NO_CYGDRIVE GIOTTO_CLASSES GIOTTO_DIR WABA_CLASSES WABA_DIR X10_CLASSES X10_DIR LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS CMD_PATH FIND GAWK JAVAC JAVA JAR JARSIGNER JAVAWS KEYTOOL CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CPP EGREP JAVADOC PTECLIPSE PTCC CXX CXXFLAGS ac_ct_CXX PTJYTHON PTJYTHON_BAT JJTREE PTCCJNI JAVAH MATLAB PTMATLAB_CC CALTROP_DIR CHIC_DIR CLASSPATHSEPARATOR COLT_DIR CMKIT_DIR ECLIPSE_CLASSPATHENTRY_PDE_REQUIREDPLUGINS ECLIPSE_DIR GC_INCLUDE_DIR GC_LD_DIRECTIVE ECLIPSE_EXCLUDING_SRC ECLIPSE_CLASSPATHENTRY_LIBS IMAGEJ_JAR JAI_JARS JAR_INDEX JAVA_SYSTEM_JAR JAVACC JAVACC_DIR JAVACV_JAR JAVAX_CRYPTO_JAR JDOCBREAKITERATOR JDOCSOURCEFLAGS JDOCTAG JDOCTAGLET JINI_DIR JINI_PRESENT JOYSTICK_JAR JTCLSH JTREE JVERSION JMF_JARS JNA_JAR JODE_CLASSES JUNIT_JAR JYTHON_DIR JXTA_DIR KIELER_JAR KVM_CLASSES KVM_DIR LEJOS_DIR LIBEXPAT_INCLUDE_DIR LIBEXPAT_LIB_DIR MAJOR_OS_NAME MATLAB_DIR MATLAB_LIBDIR MATLAB_64LIBDIR MYSQL_JAR OPENCV_JAR ORACLE_OJDBC_JAR PSDF_DIR PTBACKTRACK_DIR PTBACKTRACK_ECLIPSE_DIR PTBACKTRACK_ECLIPSE_DOC_JARS PTBACKTRACK_ECLIPSE_JARS PTBACKTRACK_ECLIPSE_PACKAGES PTBOOST_INCLUDE PTBSH_JAR PTBSH_MLC_DIR PTBSH_RUN_DIR PTBSH_PACKAGES PTCALTROP_DIR PTCHIC_DIR PTCM_DIR PTCODEGEN_OPTIONAL_PACKAGES PTCOLT_DIR PTCOLT_JARS PTCOLT_PACKAGES PTCOMM_DIR PTCOMM_PACKAGES PTCOPERNICUS_DIR PTCUNIT_DIR PTDATABASE_DIR PTDATABASE_JNLP_JARS PTDATABASE_PACKAGES PTDB_DIR PTDB_PACKAGES PTDBXML_JARS PTDBXML_LIB PTDISTRIBUTED_DIR PTDISTRIBUTED_JARS PTDISTRIBUTED_PACKAGES PTDOCLETS_DIR PTEXCEL_DIR PTEXCEL_PACKAGES PTFUZZY_DIR PTFUZZYENGINE_DIR PTFUZZY_PACKAGES PTGMP_INCLUDE PTGMP_LD_FLAGS PTGMP_LIB PTGRDOMAIN_JAR PTGR_PACKAGES PTGRO_DIR PTGRO_PACKAGES PTII PTITEXTPDF_DIR PTITEXTPDF_JAR PTITEXTPDF_PACKAGES PTJACL_DIR PTJACL_JAR PTJAI_DIR PTJAI_PACKAGES PTJAVACV_DIR PTJAVACV_PACKAGES PTJAVA_DIR PTJAVA_DIR_NO_CYGDRIVE PTJAVA_HOME PTJAVA3D_DIR PTJMF_DIR PTJMF_PACKAGES PTJNI_ARCHITECTURE PTJNI_INCLUDE PTJNI_DL_LIBRARY PTJNI_LIB_ARCHITECTURE PTJNI_NO_CYGWIN PTJNI_GCC_SHARED_FLAG PTJNI_SHAREDLIBRARY_CFLAG PTJNI_SHAREDLIBRARY_LDFLAG PTJNI_SHAREDLIBRARY_PREFIX PTJNI_SHAREDLIBRARY_SUFFIX PTJNI_LIBRARIES PTJOGL_DIR PTJOGL_JARS PTJOYSTICK_DIR PTJOYSTICK_PACKAGES PTJUNIT_PACKAGES PTJXL_JAR PTJYTHON_DIR PTJYTHON_PACKAGES PTJXTA_DIR PTOPENCV_DIR PTOPENCVCG_DIR PTOPENCV_INCLUDE_DIR PTOPENCV_PACKAGES PTKIELER_DIR PTKVM_DIR PTLBNL_DIR PTLEGO_DIR PTLEJOS_DIR PTLIBEXPAT_DIR PTMATLAB_CC_FLAGS PTMATLAB_DIR PTMATLAB_LD_ARGS PTMATLAB_64LD_ARGS PTMESCAL_DIR PTPDFRENDERER_DIR PTPDFRENDERER_JAR PTPSDF_DIR PTSVG_DIR PTSVG_JAR PTPOWERMOCK_DIR PTPOWERMOCK_JARS PTPROCESSING_JARS PTPTALON_DIR PTPTALON_PACKAGES ANTLR_DIR PTQUICKTIME_DIR PTQUICKTIME_PACKAGES PTRXTX_PACKAGES PTSPACE_DIR PTSPACEDOMAIN_JAR PTSPACEDOMAIN_PACKAGES PTTINI_DIR PTTINYOS_DIR PTGIOTTO_DIR PTWABA_DIR PTX10_DIR PTX10_PACKAGES PTII_LOCALURL QTJAVA_ZIP RXTX_JAR RXTX_PRESENT SOOT_CLASSES SOOT_DIR TINI_CLASSES TINI_DIR TOOLS_JAR TOSROOT_NO_CYGDRIVE TOSDIR_NO_CYGDRIVE GIOTTO_CLASSES GIOTTO_DIR WABA_CLASSES WABA_DIR X10_CLASSES X10_DIR LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -879,6 +879,8 @@ Optional Packages:
                           defaults to \$PTII/ptdb/lib/dbxml.jar
   --with-db=JAR       use db.jar from JAR,
                           defaults to \$PTII/ptdb/lib/db.jar
+  --with-dbxmllib=DIR    use libdbxml from DIR,
+                          defaults to \$PTII/vendors/misc/dbxml-2.5.16/install/lib
   --with-fuzzyengine=DIRECTORY       use FuzzyEngine from DIRECTORY,
                           defaults to \$PTII/vendors/misc/FuzzyEngine
   --with-gc-include=DIR       use gc.h from DIR
@@ -5586,6 +5588,28 @@ echo "${ECHO_T}$PTDB_JAR" >&6; fi
             # PTDB_PACKAGES is used in ptII/doc/makefile
 	    PTDB_PACKAGES=`find ptdb -name "*.java" | grep -v /test | awk -F / '{printf("%s", $1); for (i = 2; i < NF; i++) printf(".%s", $i); printf("\n")}' | sort | uniq | awk '{printf("%s ", $0)}'`
          fi
+    fi
+
+    # Look for shared libraries necessary at runtime.
+    echo "$as_me:$LINENO: checking for dbxml runtime shared libraries" >&5
+echo $ECHO_N "checking for dbxml runtime shared libraries... $ECHO_C" >&6
+
+# Check whether --with-dbxmllib or --without-dbxmllib was given.
+if test "${with_dbxmllib+set}" = set; then
+  withval="$with_dbxmllib"
+  PTDBXML_LIB=$withval
+else
+  PTDBXML_LIB=$PTII/vendors/misc/dbxml-2.5.16/install/lib
+fi;
+    if test  -d "$PTDBXML_LIB"; then
+	if test "${PTVERBOSE:-none}" = "none"; then echo "$as_me:$LINENO: result: ok" >&5
+echo "${ECHO_T}ok" >&6; else echo "$as_me:$LINENO: result: $PTDBXML_LIB" >&5
+echo "${ECHO_T}$PTDBXML_LIB" >&6; fi
+	libdbxml=`$FIND "$PTDBXML_LIB" -name "*dbxml-*"`
+	if test ! -f "$libdbxml"; then
+	    { echo "$as_me:$LINENO: WARNING: Failed to find dbxml-X.Y shared library in $PTDBXML_LIB" >&5
+echo "$as_me: WARNING: Failed to find dbxml-X.Y shared library in $PTDBXML_LIB" >&2;}
+        fi
     fi
 
     if test "$PTDB_DIR" = ""; then
@@ -11543,6 +11567,9 @@ fi
 # PTDBXML_JARS includes dbxml.jar and db.xml and is used by $PTII/ptdb
 
 
+# Directory that contains libdbxml-X.Y.{so,dll,dylib}.  Used in $PTII/ptdb
+
+
 # Set to distributed and used in
 # $PTII/ptolemy/makefile if jini was found
 
@@ -12682,6 +12709,7 @@ s,@PTDATABASE_PACKAGES@,$PTDATABASE_PACKAGES,;t t
 s,@PTDB_DIR@,$PTDB_DIR,;t t
 s,@PTDB_PACKAGES@,$PTDB_PACKAGES,;t t
 s,@PTDBXML_JARS@,$PTDBXML_JARS,;t t
+s,@PTDBXML_LIB@,$PTDBXML_LIB,;t t
 s,@PTDISTRIBUTED_DIR@,$PTDISTRIBUTED_DIR,;t t
 s,@PTDISTRIBUTED_JARS@,$PTDISTRIBUTED_JARS,;t t
 s,@PTDISTRIBUTED_PACKAGES@,$PTDISTRIBUTED_PACKAGES,;t t
