configure.in changed

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -676,7 +676,7 @@ fi
 #
 echo $ac_n "checking for the java runtime in $PTJAVA_DIR/bin""... $ac_c" 1>&6
 echo "configure:679: checking for the java runtime in $PTJAVA_DIR/bin" >&5
-if test -f $PTJAVA_DIR/bin/java; then
+if test -f $PTJAVA_DIR/bin/java -o -f $PTJAVA_DIR/bin/java.exe; then
     echo "$ac_t""$PTJAVA_DIR/bin/java" 1>&6
     echo $ac_n "checking that you have the right java in your path.""... $ac_c" 1>&6
 echo "configure:683: checking that you have the right java in your path." >&5
@@ -1086,6 +1086,30 @@ echo "configure:1071: checking for how to run jacl" >&5
 fi
 
 #--------------------------------------------------------------------
+#	Test for javax.sound
+#--------------------------------------------------------------------
+# PTJAVASOUND_DIR is set to javasound and used in 
+# $PTII/ptolemy/actor/lib/makefile if javasound was found
+PTJAVASOUND_DIR=
+
+echo $ac_n "checking for javax.sound""... $ac_c" 1>&6
+echo "configure:1097: checking for javax.sound" >&5
+# We need to run javac in the config directory so that javac from jdk1.1.6
+# under NT and cygwin works properly
+startdir=`pwd`
+cd $srcdir/config
+# Don't use 'env $JAVAC . . .' here, it will not work under Cygwin
+if $JAVAC javasoundTest.java ; then
+    echo "$ac_t""ok" 1>&6
+    PTJAVASOUND=javasound	
+else
+   echo "configure: warning: '$JAVAC javasoundTest.java' failed.  Perhaps you are running
+  under JDK1.2?  javasound is used in actor.lib, but you can probably
+  get away without it." 1>&2
+fi
+cd $startdir
+
+#--------------------------------------------------------------------
 #       Jini is connection technology from Sun, see http://www.sun.com/jini/
 #       See if there was a command-line option for where Jini is
 #       If not, look in $PTII/vendors/sun/jini/jini1_0_1
@@ -1106,7 +1130,7 @@ if test ! -d "$JINI_USER_DIR"; then
     JINI_DIR='\$PTII/vendors/sun/jini/jini1_0_1'
 else
     echo $ac_n "checking for jini directory""... $ac_c" 1>&6
-echo "configure:1110: checking for jini directory" >&5
+echo "configure:1134: checking for jini directory" >&5
     # Check whether --with-jini or --without-jini was given.
 if test "${with_jini+set}" = set; then
   withval="$with_jini"
@@ -1157,7 +1181,7 @@ find the PalmOS kvm" 1>&6
     KVM_CLASSES='$(KVM_DIR)/bin/api/classes'
 else
     echo $ac_n "checking for kvm directory""... $ac_c" 1>&6
-echo "configure:1161: checking for kvm directory" >&5
+echo "configure:1185: checking for kvm directory" >&5
     # Check whether --with-kvm or --without-kvm was given.
 if test "${with_kvm+set}" = set; then
   withval="$with_kvm"
@@ -1170,7 +1194,7 @@ fi
     if test -d "$KVM_DIR"; then
 	echo "$ac_t""$KVM_DIR" 1>&6
         echo $ac_n "checking for \$KVM_DIR/bin/api/classes""... $ac_c" 1>&6
-echo "configure:1174: checking for \$KVM_DIR/bin/api/classes" >&5
+echo "configure:1198: checking for \$KVM_DIR/bin/api/classes" >&5
 	if test -d "$KVM_DIR/bin/api/classes"; then
 	    KVM_CLASSES='$(KVM_DIR)/bin/api/classes'
 	    echo "$ac_t""$KVM_CLASSES" 1>&6
@@ -1180,13 +1204,13 @@ echo "configure:1174: checking for \$KVM_DIR/bin/api/classes" >&5
     else    
 	echo "$ac_t""Not found in $KVM_DIR" 1>&6
 	echo $ac_n "checking for kvm directory in /j2me_cldc""... $ac_c" 1>&6
-echo "configure:1184: checking for kvm directory in /j2me_cldc" >&5
+echo "configure:1208: checking for kvm directory in /j2me_cldc" >&5
 	# Likely place for kvm under windows
 	KVM_DIR=/j2me_cldc
         if test -d "$KVM_DIR"; then
 	    echo "$ac_t""$KVM_DIR" 1>&6
             echo $ac_n "checking for \$KVM_DIR/bin/api/classes""... $ac_c" 1>&6
-echo "configure:1190: checking for \$KVM_DIR/bin/api/classes" >&5
+echo "configure:1214: checking for \$KVM_DIR/bin/api/classes" >&5
 	    if test -d "$KVM_DIR/bin/api/classes"; then
 	        KVM_CLASSES='$(KVM_DIR)/bin/api/classes'
 	        echo "$ac_t""$KVM_CLASSES" 1>&6
@@ -1259,6 +1283,10 @@ fi
 
 
 # Location of the JDK
+
+
+# Set to javasound and used in 
+# $PTII/ptolemy/actor/lib/makefile if javasound was found
 
 
 # Set to jspaces and used in 
@@ -1438,6 +1466,7 @@ s%@KVM_DIR@%$KVM_DIR%g
 s%@PTJACL_JAR@%$PTJACL_JAR%g
 s%@PTJACL_JFLAG@%$PTJACL_JFLAG%g
 s%@PTJAVA_DIR@%$PTJAVA_DIR%g
+s%@PTJAVASOUND_DIR@%$PTJAVASOUND_DIR%g
 s%@PTJSPACES_DIR@%$PTJSPACES_DIR%g
 s%@PTKVM_DIR@%$PTKVM_DIR%g
 s%@PTLEGO_DIR@%$PTLEGO_DIR%g
