configure.in changed

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -826,6 +826,7 @@ PTPDFRENDERER_JAR
 PTPSDF_DIR
 PTSVG_DIR
 PTSVG_JAR
+PTPROCESSING_JARS
 PTPTALON_DIR
 PTPTALON_PACKAGES
 ANTLR_DIR
@@ -8258,7 +8259,8 @@ echo "$as_me: WARNING: Not including
     the OpenCV files.
     This is only a problem if you are using Eclipse.
     If the class was in the JRE, then Eclipse should compile the OpenCV files
-    without problems" >&5
+    without problems.
+    For details, see $PTII/ptolemy/actor/lib/opencv/package.html" >&5
 echo "$as_me: WARNING: Either we could not find
     hypermedia.video.OpenCV or else it was already in the JRE.
     Searching for OpenCV.jar returned:
@@ -8267,9 +8269,71 @@ echo "$as_me: WARNING: Either we could not find
     the OpenCV files.
     This is only a problem if you are using Eclipse.
     If the class was in the JRE, then Eclipse should compile the OpenCV files
-    without problems" >&2;}
+    without problems.
+    For details, see $PTII/ptolemy/actor/lib/opencv/package.html" >&2;}
 	       OPENCV_JAR=
             fi
+
+
+            { echo "$as_me:$LINENO: checking for Processing Library" >&5
+echo $ECHO_N "checking for Processing Library... $ECHO_C" >&6; }
+	    if "$JAVAC" FindClass.java ; then
+	        # Usually opencv.jar will be in the CLASSPATH
+	        PROCESSING_CORE_JAR=`CLASSPATH="$PTII/config$CLASSPATHSEPARATOR$CLASSPATH" "$JAVA" FindClass processing.core.PImage`
+		if test -f "$PROCESSING_CORE_JAR"; then
+		    if test "${PTVERBOSE:-none}" = "none"; then { echo "$as_me:$LINENO: result: ok" >&5
+echo "${ECHO_T}ok" >&6; }; else { echo "$as_me:$LINENO: result: $PROCESSING_CORE_JAR" >&5
+echo "${ECHO_T}$PROCESSING_CORE_JAR" >&6; }; fi
+   		    PTPROCESSING_JARS=$PROCESSING_CORE_JAR
+                    case "`uname -s`" in
+	       	    Darwin)
+  	                { echo "$as_me:$LINENO: WARNING: Not including
+   $PROCESSING_CORE_JAR
+   in the Eclipse classpath under Darwin because it is already present." >&5
+echo "$as_me: WARNING: Not including
+   $PROCESSING_CORE_JAR
+   in the Eclipse classpath under Darwin because it is already present." >&2;}
+      	  	        ;;
+               	    *)
+		        ECLIPSE_CLASSPATHENTRY_LIBS="$ECLIPSE_CLASSPATHENTRY_LIBS \
+			       <classpathentry kind=\"lib\" path=\"$PROCESSING_CORE_JAR\"/> "
+		        ;;
+                    esac
+                else
+	            PTOPENCV_DIR=
+       	       { echo "$as_me:$LINENO: WARNING: Either we could not find
+    processing.core.PImage or else it was already in the JRE.
+    Searching for PImage returned:
+      $PROCESSING_CORE_JAR
+    If the class cannot be found, then Eclipse might not be able to find
+    the Processing files.
+    This is only a problem if you are using Eclipse.
+    If the class was in the JRE, then Eclipse should compile the OpenCV files
+    without problems
+    Processing is the image source processing library from
+    http://processing.org.  It is used by the
+    vision actors in ptolemy/actor/lib/opencv/.
+    These actors are optional, but require Processing.
+    For details, see $PTII/ptolemy/actor/lib/opencv/package.html" >&5
+echo "$as_me: WARNING: Either we could not find
+    processing.core.PImage or else it was already in the JRE.
+    Searching for PImage returned:
+      $PROCESSING_CORE_JAR
+    If the class cannot be found, then Eclipse might not be able to find
+    the Processing files.
+    This is only a problem if you are using Eclipse.
+    If the class was in the JRE, then Eclipse should compile the OpenCV files
+    without problems
+    Processing is the image source processing library from
+    http://processing.org.  It is used by the
+    vision actors in ptolemy/actor/lib/opencv/.
+    These actors are optional, but require Processing.
+    For details, see $PTII/ptolemy/actor/lib/opencv/package.html" >&2;}
+    		    PROCESSING_CORE_JAR=
+    	            ECLIPSE_EXCLUDING_SRC="$ECLIPSE_EXCLUDING_SRC|ptolemy/actor/lib/opencv/javacv/"
+                 fi
+    	    fi
+
 
 	    # Look for JavaCV, which is GPL'd
 	    JAVACV_JAR=
@@ -8363,7 +8427,6 @@ fi
 if test -z "$PTOPENCV_DIR"; then
    ECLIPSE_EXCLUDING_SRC="$ECLIPSE_EXCLUDING_SRC|ptolemy/actor/lib/opencv/"
 fi
-
 
 # PTCGOPENCV_DIR is set to OpenCVTracking and used in
 # $PTII/ptolemy/codegen/demo/makefile if opencv was found
@@ -11953,6 +12016,9 @@ fi
 # Jar file used by diva/util/java2d/svg/makefile
 
 
+# Jar files used by the Image Processing library from http://processing.org
+
+
 # PTPTALON_DIR is set to ptalon and used in
 # $PTII/ptolemy/actor/makefile if antlr.jar was found.
 
@@ -13013,6 +13079,7 @@ PTPDFRENDERER_JAR!$PTPDFRENDERER_JAR$ac_delim
 PTPSDF_DIR!$PTPSDF_DIR$ac_delim
 PTSVG_DIR!$PTSVG_DIR$ac_delim
 PTSVG_JAR!$PTSVG_JAR$ac_delim
+PTPROCESSING_JARS!$PTPROCESSING_JARS$ac_delim
 PTPTALON_DIR!$PTPTALON_DIR$ac_delim
 PTPTALON_PACKAGES!$PTPTALON_PACKAGES$ac_delim
 ANTLR_DIR!$ANTLR_DIR$ac_delim
@@ -13052,7 +13119,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 55; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 56; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
