Added PTJNI_LIB_ARCHITECTURE so that we can run jni launcher under Solaris

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -310,7 +310,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS CMD_PATH FIND JAVAC JAVA CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CPP EGREP PTECLIPSE PTCC CXX CXXFLAGS ac_ct_CXX JJTREE MATLAB PTMATLAB_CC CALTROP_DIR CHIC_DIR CLASSPATHSEPARATOR COLT_DIR CMKIT_DIR COMMAPI_DIR COMMAPI_PRESENT ECLIPSE_DIR GC_INCLUDE_DIR GC_LD_DIRECTIVE ECLIPSE_EXCLUDING_SRC ECLIPSE_CLASSPATHENTRY_LIBS IMAGEJ_JAR JAI_JARS JAR_INDEX JAVA_SYSTEM_JAR JAVACC JAVACC_DIR JAVAX_CRYPTO_JAR JDOCBREAKITERATOR JDOCTAGLET JHDL_JAR JINI_DIR JINI_PRESENT JOYSTICK_JAR JTCLSH JTREE JVERSION JMF_JARS JODE_CLASSES JYTHON_DIR JXTA_DIR KVM_CLASSES KVM_DIR LEJOS_DIR MAJOR_OS_NAME MATLAB_DIR MATLAB_LIBDIR PSDF_DIR PTBACKTRACK_ECLIPSE_DIR PTBACKTRACK_ECLIPSE_DOC_JARS PTBACKTRACK_ECLIPSE_JARS PTBACKTRACK_ECLIPSE_PACKAGES PTBOOST_INCLUDE PTCALTROP_DIR PTCHIC_DIR PTCM_DIR PTCOLT_DIR PTCOLT_JARS PTCOLT_PACKAGES PTCOMM_DIR PTCOMM_PACKAGES PTCOPERNICUS_DIR PTDISTRIBUTED_DIR PTDISTRIBUTED_JARS PTDISTRIBUTED_PACKAGES PTDOCLETS_DIR PTGMP_INCLUDE PTGMP_LD_FLAGS PTGMP_LIB PTGRDOMAIN_JAR PTGR_PACKAGES PTII PTJACL_DIR PTJACL_JAR PTJAI_DIR PTJAI_PACKAGES PTJAVA_DIR PTJAVA_DIR_NO_CYGDRIVE PTJAVA_HOME PTJAVA3D_DIR PTJHDL_DIR PTJMF_DIR PTJMF_PACKAGES PTJNI_DIR PTJNI_ARCHITECTURE PTJNI_NO_CYGWIN PTJNI_SHAREDLIBRARY_CFLAG PTJNI_SHAREDLIBRARY_LDFLAG PTJNI_SHAREDLIBRARY_PREFIX PTJNI_SHAREDLIBRARY_SUFFIX PTJNI_LIBRARIES PTJOYSTICK_DIR PTJOYSTICK_PACKAGES PTJYTHON_DIR PTJXTA_DIR PTKVM_DIR PTLEGO_DIR PTLEJOS_DIR PTMATLAB_DIR PTMATLAB_LD_ARGS PTMESCAL_DIR PTPSDF_DIR PTSVG_DIR PTSVG_JAR PTQUICKTIME_DIR PTQUICKTIME_PACKAGES PTTINI_DIR PTTINYOS_DIR PTGIOTTO_DIR PTVR_DIR PTVR_JAR PTVR_PACKAGES PTWABA_DIR PTX10_DIR PTX10_PACKAGES PTII_LOCALURL QTJAVA_ZIP SOOT_CLASSES SOOT_DIR TINI_CLASSES TINI_DIR TOOLS_JAR TOSROOT_NO_CYGDRIVE TOSDIR_NO_CYGDRIVE GIOTTO_CLASSES GIOTTO_DIR WABA_CLASSES WABA_DIR X10_CLASSES X10_DIR LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS CMD_PATH FIND JAVAC JAVA CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CPP EGREP PTECLIPSE PTCC CXX CXXFLAGS ac_ct_CXX JJTREE MATLAB PTMATLAB_CC CALTROP_DIR CHIC_DIR CLASSPATHSEPARATOR COLT_DIR CMKIT_DIR COMMAPI_DIR COMMAPI_PRESENT ECLIPSE_DIR GC_INCLUDE_DIR GC_LD_DIRECTIVE ECLIPSE_EXCLUDING_SRC ECLIPSE_CLASSPATHENTRY_LIBS IMAGEJ_JAR JAI_JARS JAR_INDEX JAVA_SYSTEM_JAR JAVACC JAVACC_DIR JAVAX_CRYPTO_JAR JDOCBREAKITERATOR JDOCTAGLET JHDL_JAR JINI_DIR JINI_PRESENT JOYSTICK_JAR JTCLSH JTREE JVERSION JMF_JARS JODE_CLASSES JYTHON_DIR JXTA_DIR KVM_CLASSES KVM_DIR LEJOS_DIR MAJOR_OS_NAME MATLAB_DIR MATLAB_LIBDIR PSDF_DIR PTBACKTRACK_ECLIPSE_DIR PTBACKTRACK_ECLIPSE_DOC_JARS PTBACKTRACK_ECLIPSE_JARS PTBACKTRACK_ECLIPSE_PACKAGES PTBOOST_INCLUDE PTCALTROP_DIR PTCHIC_DIR PTCM_DIR PTCOLT_DIR PTCOLT_JARS PTCOLT_PACKAGES PTCOMM_DIR PTCOMM_PACKAGES PTCOPERNICUS_DIR PTDISTRIBUTED_DIR PTDISTRIBUTED_JARS PTDISTRIBUTED_PACKAGES PTDOCLETS_DIR PTGMP_INCLUDE PTGMP_LD_FLAGS PTGMP_LIB PTGRDOMAIN_JAR PTGR_PACKAGES PTII PTJACL_DIR PTJACL_JAR PTJAI_DIR PTJAI_PACKAGES PTJAVA_DIR PTJAVA_DIR_NO_CYGDRIVE PTJAVA_HOME PTJAVA3D_DIR PTJHDL_DIR PTJMF_DIR PTJMF_PACKAGES PTJNI_DIR PTJNI_ARCHITECTURE PTJNI_LIB_ARCHITECTURE PTJNI_NO_CYGWIN PTJNI_SHAREDLIBRARY_CFLAG PTJNI_SHAREDLIBRARY_LDFLAG PTJNI_SHAREDLIBRARY_PREFIX PTJNI_SHAREDLIBRARY_SUFFIX PTJNI_LIBRARIES PTJOYSTICK_DIR PTJOYSTICK_PACKAGES PTJYTHON_DIR PTJXTA_DIR PTKVM_DIR PTLEGO_DIR PTLEJOS_DIR PTMATLAB_DIR PTMATLAB_LD_ARGS PTMESCAL_DIR PTPSDF_DIR PTSVG_DIR PTSVG_JAR PTQUICKTIME_DIR PTQUICKTIME_PACKAGES PTTINI_DIR PTTINYOS_DIR PTGIOTTO_DIR PTVR_DIR PTVR_JAR PTVR_PACKAGES PTWABA_DIR PTX10_DIR PTX10_PACKAGES PTII_LOCALURL QTJAVA_ZIP SOOT_CLASSES SOOT_DIR TINI_CLASSES TINI_DIR TOOLS_JAR TOSROOT_NO_CYGDRIVE TOSDIR_NO_CYGDRIVE GIOTTO_CLASSES GIOTTO_DIR WABA_CLASSES WABA_DIR X10_CLASSES X10_DIR LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -6670,6 +6670,35 @@ echo "$as_me: WARNING: \"$PTJAVA_HOME/../include/$PTJNI_ARCHITECTURE\" was not f
 echo "${ECHO_T}$PTJAVA_HOME/../include/$PTJNI_ARCHITECTURE" >&6
     fi
 
+    echo "$as_me:$LINENO: checking for the proper JNI architecture" >&5
+echo $ECHO_N "checking for the proper JNI architecture... $ECHO_C" >&6
+    case "`uname -p`" in
+	*86) PTJNI_LIB_ARCHITECTURE=i386;;
+	sparc) PTJNI_LIB_ARCHITECTURE=sparc;;
+	unknown) if test $PTJNI_ARCHITECTURE = "win32"; then
+		     PTJNI_LIB_ARCHITECTURE=i386
+		 else
+		     PTJNI_LIB_ARCHITECTURE=unknown
+		 fi
+                 ;;
+	*) PTJNI_LIB_ARCHITECTURE=unknown;;
+    esac
+
+    echo "$as_me:$LINENO: result: '$PTJNI_LIB_ARCHITECTURE'" >&5
+echo "${ECHO_T}'$PTJNI_LIB_ARCHITECTURE'" >&6
+
+    echo "$as_me:$LINENO: checking for the proper JNI architecture lib directory" >&5
+echo $ECHO_N "checking for the proper JNI architecture lib directory... $ECHO_C" >&6
+    if test ! -d "$PTJAVA_HOME/lib/$PTJNI_LIB_ARCHITECTURE"; then
+	{ echo "$as_me:$LINENO: WARNING: \"$PTJAVA_HOME/lib/$PTJNI_LIB_ARCHITECTURE\" was not found.
+    As a result, $PTII/jni/launcher/launcher might not work." >&5
+echo "$as_me: WARNING: \"$PTJAVA_HOME/lib/$PTJNI_LIB_ARCHITECTURE\" was not found.
+    As a result, $PTII/jni/launcher/launcher might not work." >&2;}
+    else
+	echo "$as_me:$LINENO: result: $PTJAVA_HOME/lib/$PTJNI_ARCHITECTURE" >&5
+echo "${ECHO_T}$PTJAVA_HOME/lib/$PTJNI_ARCHITECTURE" >&6
+    fi
+
     echo "$as_me:$LINENO: checking for if the -mno-cygwin flag is available" >&5
 echo $ECHO_N "checking for if the -mno-cygwin flag is available... $ECHO_C" >&6
     case "`uname -s`" in
@@ -8390,6 +8419,10 @@ fi
 # $PTII/makefile if gcc or cc was found
 
 
+
+# JNI lib architecture, used to run jni/launcher
+
+
 # Flag to use with TinyOS under Cygwin (-mno-cygwin)
 
 
@@ -9296,6 +9329,7 @@ s,@PTJMF_DIR@,$PTJMF_DIR,;t t
 s,@PTJMF_PACKAGES@,$PTJMF_PACKAGES,;t t
 s,@PTJNI_DIR@,$PTJNI_DIR,;t t
 s,@PTJNI_ARCHITECTURE@,$PTJNI_ARCHITECTURE,;t t
+s,@PTJNI_LIB_ARCHITECTURE@,$PTJNI_LIB_ARCHITECTURE,;t t
 s,@PTJNI_NO_CYGWIN@,$PTJNI_NO_CYGWIN,;t t
 s,@PTJNI_SHAREDLIBRARY_CFLAG@,$PTJNI_SHAREDLIBRARY_CFLAG,;t t
 s,@PTJNI_SHAREDLIBRARY_LDFLAG@,$PTJNI_SHAREDLIBRARY_LDFLAG,;t t
