better checks for /home/eecs/cxh/ptII being set wrong, check for -native only if JDK1.2*

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -65,8 +65,33 @@ if test  ! -w "$PTII"; then
     echo "Windows, then you might be able to ignore this problem and"
     echo "proceed with the build.  If you continue to have problems,"
     echo "try upgrading to cygwin1.1.0 or later"
+fi
 
+AC_MSG_CHECKING([if $PTII contains "cygdrive"])
+echo "$PTII" | grep cygdrive > /dev/null
+status=$?
+if test "$status" -eq 1 ; then
+    AC_MSG_RESULT([ok
+  $PTII does not contain cygdrive, which is right.])
+else
+    AC_MSG_WARN([\$PTII == $PTII,
+which contains "cygdrive".
 
+It could be that you have incorrectly set PTII.
+If you have installed Cygwin in c:/cygwin, and your Ptolemy II installation
+is in a directory outside of the c:/cygwin tree, then Cygwin may
+change your PTII variable to include "/cygdrive/c".  This
+will cause problems with non-Cygwin tools like javac that do
+not understand /cygdrive/c
+
+Under Cygwin, try setting PTII in the control panel 
+(Start->Control Panels->Advanced->Environment Variables)
+or it with backslashes:
+  PTII=c:\\\\users\\\\yourname\\\\ptII
+  export PTII
+and then rerun
+  ./configure
+See $PTII/doc/install.htm for details.'])
 fi
 
 PTII_DEFAULT=$PTII
@@ -116,13 +141,13 @@ so we search for the java compiler.])
     if test ! -d "$PTJAVA_DIR"; then
 	DEFAULT_JDK=/opt/jdk1.2.2
 	if test -d "$DEFAULT_JDK"; then
-	    PTJAVA_DIR=`cd $DEFAULT_JDK; pwd`
+	    PTJAVA_DIR=`cd "$DEFAULT_JDK"; pwd`
 	    AC_MSG_WARN(['${PTJAVA_DIR}' is not a directory, using the default '${DEFAULT_JDK}'])
 
 	else
 	    DEFAULT_JDK=/usr/java
 	    if test -d "$DEFAULT_JDK"; then
-		PTJAVA_DIR=`cd $DEFAULT_JDK; pwd`
+		PTJAVA_DIR=`cd "$DEFAULT_JDK"; pwd`
 		AC_MSG_WARN(['${PTJAVA_DIR}' is not a directory, using the default '${DEFAULT_JDK}'])
 	    else
 			    AC_MSG_ERROR([
@@ -204,20 +229,41 @@ JVERSION=unknown
 # under NT and cygwin works properly
 startdir=`pwd`
 cd "$srcdir/config"
-# Don't use 'env $JAVAC . . .' here, it will not work under Cygwin
 if "$JAVAC" confTest.java ; then
     AC_MSG_RESULT(ok)
 
     AC_MSG_CHECKING([the value of the java.version Property ])
-    # Strip out the JDK1.3beta messages under Solaris2.5.1
-    JVERSION=`CLASSPATH=$PTII/config "$JAVA" confTest |
-	grep -v "Warning! The libthread.so on your system is an older version than" |
-	grep -v "the one this VM was tested with. Please read the install documentation for" |
-	grep -v "patch installation instructions."`
-    AC_MSG_RESULT($JVERSION)
-
+    # Older versions of cygwin might not have env, but 1.1 does
+    if env CLASSPATH=$PTII/config "$JAVA" confTest > /dev/null; then
+	# Run it again and get the results
+	JVERSION=`CLASSPATH=$PTII/config "$JAVA" confTest`
+	AC_MSG_RESULT($JVERSION)
+    else	
+	AC_MSG_ERROR(['CLASSPATH=$PTII/config $JAVA confTest failed.
+If java fails, then you will not be able to run Ptolemy II.
+This could be because your PTII variable is set incorrectly.
+Under Cygwin, try setting PTII in the control panel 
+(Start->Control Panels->Advanced->Environment Variables)
+or it with backslashes:
+  PTII=c:\\\\users\\\\yourname\\\\ptII
+  export PTII
+and then rerun
+  ./configure
+See $PTII/doc/install.htm for details.'])
+   fi
 else
-   AC_MSG_WARN(['"$JAVAC" confTest.java' failed'])
+   AC_MSG_ERROR(['CLASSPATH=$PTII/config $JAVAC confTest.java failed.
+If javac fails, then you will not be able to compile Ptolemy II.
+This could be because your PTII variable is set incorrectly.
+Under Cygwin, try setting PTII in the control panel 
+(Start->Control Panels->Advanced->Environment Variables)
+or it with backslashes:
+  PTII=c:\\\\users\\\\yourname\\\\ptII
+  export PTII
+and then rerun
+  ./configure
+See $PTII/doc/install.htm for details.'])
+
 fi
 cd "$startdir"
 
@@ -231,6 +277,10 @@ JDOCSIZE=
 case "$JVERSION" in
 	1.2.*)  JDOCSIZE="-J-Xmx132m"
 		AC_MSG_RESULT([yes, use $JDOCSIZE])
+		# The reference version of JDK 1.2 has a -native flag
+		# If we don't use -native, then some of the threading
+		# tests fail.
+		PTJACL_JFLAG=-native
 	;;
 	*) AC_MSG_RESULT([no, not necessary])
 	;;
@@ -326,6 +376,55 @@ fi
 
 
 #--------------------------------------------------------------------
+#       Lejos is a Java Virtual machine that runs on the Lego Mindstorm
+#	For more information, see http://lejos.sourceforge.net
+#	See if there was a command-line option for commapi is
+#       If not, check to see if $PTII/vendors/lejos/lejos/lejosBeta3
+#--------------------------------------------------------------------
+
+# We only need to look for commapi if $PTII/ptolemy/apps/lejos
+LEJOS_USER_DIR="$PTII/ptolemy/apps/lejos"
+LEJOS_PRESENT=no
+# PTLEJOS_DIR is set to lejos
+# $PTII/ptolemy/apps/makefile if the Java Communications API was found
+PTLEJOS_DIR=
+if test ! -d "$LEJOS_USER_DIR"; then
+    AC_MSG_RESULT([$COMMAPI_USER_DIR is not present, so we need not
+find lejos])
+    # Use curly brackets around PTII so that if lejos is not present
+    # then ${PTII} will appear in ptinvoke.
+    LEJOS_DIR='${PTII}/vendors/lejos/lejosBeta3'
+else
+    if test "$COMMAPI_PRESENT" = "no"; then
+        AC_MSG_WARN(['Lejos requires commapi, which was not found'])
+    else 
+	AC_MSG_CHECKING([for lejos directory])
+	AC_ARG_WITH(LEJOS, [  --with-lejos=DIR       use Java lejos from DIR,
+                          defaults to \$PTII/vendors/lejos/lejosBeta3],
+		LEJOS_DIR=$withval,
+		LEJOS_DIR=$PTII/vendors/lejos/lejosBeta3)
+
+	if test -d "$LEJOS_DIR/classes/josx"; then
+	    AC_MSG_RESULT([$LEJOS_DIR])
+	    # Subdirectory that contains Java Communications API specific code
+	    PTLEJOS_DIR=lejos
+	    LEJOS_PRESENT=yes
+	else
+	    AC_MSG_WARN(['Failed to find $LEJOS_DIR/classes/josx/'])
+	    LEJOS_DIR='${PTII}/vendors/lejos'
+	fi
+    fi	
+    if test "$LEJOS_PRESENT" = "no"; then
+	AC_MSG_WARN(['Perhaps Lejos is not installed?
+	You need not download Lejos unless you plan on use the Lego Mindstorm
+	demos in \$PTII/ptolemy/apps/lejos. Lejos can be downloaded from
+	http://lejos.sourceforge.net
+	and placed  in \$PTII/vendors/lejos/lejosBeta3'])
+    fi
+fi
+
+
+#--------------------------------------------------------------------
 #	See if there was a command-line option for where javacc is;  if
 #	not, check to see if $PTII/vendors/sun/JavaCC exists
 #       if it is does not, look for javacc on the path.
@@ -403,9 +502,8 @@ fi
 # exists.  If we are shipping ptplot, then this directory might not
 # exist
 PTJACL_JAR=$PTII/lib/ptjacl.jar
-# The reference version of JDK 1.2 has a -native flag
-# If we don't use -native, then some of the threading tests fail
-PTJACL_JFLAG=-native
+# If we are running under JDK1.2.*, then PTJACL_JFLAG is defined
+# above to be -native
 JTCLSH='["$(JAVA)" $(PTJACL_JFLAG) tcl.lang.Shell]'
 
 if test ! -d "$PTII/util/testsuite"; then
@@ -810,6 +908,10 @@ AC_SUBST(KVM_CLASSES)
 # Directory that contains the kvm used by PalmOS
 AC_SUBST(KVM_DIR)
 
+# Set to the location of the lejos installation, usually in
+# $PTII/vendors/lejos
+AC_SUBST(LEJOS_DIR)
+
 # ptjacl.jar file, used to run the test suites
 AC_SUBST(PTJACL_JAR)
 
@@ -838,6 +940,11 @@ AC_SUBST(PTKVM_DIR)
 # Set to lego and used in
 # $PTII/ptolemy/apps/makefile if the Java Communications API was found
 AC_SUBST(PTLEGO_DIR)
+
+# Set to lejos and used in
+# $PTII/ptolemy/apps/makefile if the Java Communications API was found
+# and Legos was found
+AC_SUBST(PTLEJOS_DIR)
 
 # Set to tini and used in
 # $PTII/ptolemy/apps/makefile if TINI was found
