Added -h, -v and ability to take directories from command line

diff --git a/ptolemy/domains/ptinyos/util/nc2moml/nc2moml b/ptolemy/domains/ptinyos/util/nc2moml/nc2moml
--- a/ptolemy/domains/ptinyos/util/nc2moml/nc2moml
+++ b/ptolemy/domains/ptinyos/util/nc2moml/nc2moml
@@ -1,4 +1,32 @@
 #!/bin/sh
+# Shell script that converts PtinyOS .nc files to Ptolemy .moml files
+# Authors:  Elaine Cheong, Christopher Brooks
+# Version: $Id$
+#
+# Copyright (c) 2005 The Regents of the University of California.
+# 	All Rights Reserved.
+#
+# Permission is hereby granted, without written agreement and without
+# license or royalty fees, to use, copy, modify, and distribute this
+# software and its documentation for any purpose, provided that the
+# above copyright notice and the following two paragraphs appear in all
+# copies of this software.
+#
+# IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY
+# FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
+# ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
+# THE UNIVERSITY OF CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF
+# SUCH DAMAGE.
+#
+# THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
+# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
+# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE
+# PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
+# CALIFORNIA HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
+# ENHANCEMENTS, OR MODIFICATIONS.
+#
+# 						PT_COPYRIGHT_VERSION_2
+# 						COPYRIGHTENDKEY
 
 # Set up the args to convert .nc files to .moml files.
 
@@ -11,18 +39,67 @@ DIR_LIST="tos/lib tos/system tos/platform tos/sensorboards"
 # turn on verbose output.
 export NC2MOML_VERBOSE=0
 
+# ${1#-} will not work under Solaris 8
+#while [ "${1#-}" != "$1" ]; do
+# jode takes a -d argument, which causes problems unless we use "x..."
+while [ "x$1" != "x" -a  "x`echo $1 | egrep '^-'`" = "x$1" -a $# -gt 0 ]; do
+    case $1 in
+        -h|-help|--help)
+	    shift    
+	    echo "$0: Usage: $0 -v|-h [PtinyOS_Directory] . . ."
+	    echo "    Convert the PtinyOS files in 'PtinyOS_Directory' to moml."
+	    echo "    If no directory names are present in the command line,"
+	    echo "    then we process these directories:"
+	    echo "        $DIR_LIST"
+	    echo "    Flags:"
+	    echo "        -h print this help message"
+	    echo "        -v verbose"
+	    echo "    Debugging output ends up in $MOML_OUTPUT_DIR/command.txt"
+	    echo "    This script requires that \$TOSROOT be set to the"
+	    echo "    location of the TinyOS tree,"
+	    echo "    typically \"\$PTII/vendors/ptinyos/tinyos-1.x\"."
+	    echo "    For a quick test, run \"$0 tos/lib/Counters\"."
+	    exit 0
+            ;;
+
+        -v|-verbose|--verbose)
+            shift
+	    set -x
+            NC2MOML_VERBOSE=1
+            continue
+            ;;
+	*)
+	    echo "$0: Error: Don't understand '$1' argument, run with -h for help"
+	    exit 3
+	    ;;
+    esac
+done
+
+if [ $# -gt 0 ]; then 
+    DIR_LIST="" 
+    # Accumulate another arguments and set DIRLIST
+    while [ "x$1" != "x" ]; do
+        # FIXME: what about directories with spaces in their names?
+        DIR_LIST="$DIR_LIST \"$1\"";
+        shift    
+    done
+fi
+
 ####################
 
 if [ -z $TOSROOT ]; then
-  echo "Error: \$TOSROOT must be defined"
-  exit 0
+  echo "$0: Error: \$TOSROOT must be defined"
+  echo "    \$TOSROOT should be set to the tinyos tree,"
+  echo "    typically \"\$PTII/vendors/ptinyos/tinyos-1.x\""
+  exit 1
 fi
 TOS_INPUT_DIR=$TOSROOT
 
 if [ -z $PTII ]; then
-  echo "Error: \$PTII must be defined"
+  echo "$0: Error: \$PTII must be defined"
+  exit 2
 fi
 
-echo "$SRC_DIR/nc2moml-main $TOS_INPUT_DIR \\\''\$CLASSPATH'\\\' $MOML_OUTPUT_DIR $DIR_LIST"
+echo "Running $SRC_DIR/nc2moml-main $TOS_INPUT_DIR \\\''\$CLASSPATH'\\\' $MOML_OUTPUT_DIR $DIR_LIST"
 
 $SRC_DIR/nc2moml-main $TOS_INPUT_DIR \\\''\$CLASSPATH'\\\' $MOML_OUTPUT_DIR $DIR_LIST
